use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let apis = vec![
        // ── Market Data ──────────────────────────────────────────────
        ("binance_rest", "Binance REST API", "Market data, order placement, account info — 1200 req/min", "exchange",
         vec!["data", "binance", "rest", "crypto"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.binance.com/api/v3".into() }),
        ("binance_ws", "Binance WebSocket", "Real-time market data streams — 1024 streams per connection", "exchange",
         vec!["data", "binance", "websocket", "real-time"], Complexity::Intermediate,
         Implementation::WebSocket { url: "wss://stream.binance.com:9443/ws".into() }),
        ("coinbase", "Coinbase Advanced Trade API", "Spot and perpetual futures — US-regulated exchange", "exchange",
         vec!["data", "coinbase", "rest", "regulated"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.coinbase.com/api/v3".into() }),
        ("kraken", "Kraken REST API", "Spot and futures — 15+ crypto pairs with staking", "exchange",
         vec!["data", "kraken", "rest", "spot"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.kraken.com/0/public".into() }),
        ("bybit", "Bybit REST API", "Perpetuals, options, spot — high-leverage derivatives", "exchange",
         vec!["data", "bybit", "rest", "derivatives"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.bybit.com/v5".into() }),
        ("okx", "OKX REST API", "Spot, futures, options, DeFi — comprehensive exchange", "exchange",
         vec!["data", "okx", "rest", "derivatives"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.okx.com/api/v5".into() }),
        ("coingecko", "CoinGecko API", "Token data, market cap, volume — 30 calls/min free", "market-info",
         vec!["data", "coingecko", "free", "market-cap"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.coingecko.com/api/v3".into() }),
        ("coincap", "CoinCap API", "Real-time crypto prices, historical data — free tier", "market-info",
         vec!["data", "coincap", "free", "real-time"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.coincap.io/v2".into() }),
        ("messari", "Messari API", "Research-grade crypto data — fundamentals, on-chain, governance", "market-info",
         vec!["data", "messari", "fundamentals", "research"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://data.messari.io/api/v1".into() }),
        ("alpha_vantage", "Alpha Vantage API", "Stocks, forex, crypto indicators — 25 req/day free", "market-info",
         vec!["data", "alpha-vantage", "free", "indicators"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.alphavantage.co/query".into() }),
        ("polygon", "Polygon.io API", "Stocks, options, forex, crypto — 5 req/min free", "market-info",
         vec!["data", "polygon", "stocks", "options"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.polygon.io/v2".into() }),
        ("finnhub", "Finnhub API", "Stocks, forex, crypto — real-time WebSocket, free tier 60 calls/min", "market-info",
         vec!["data", "finnhub", "free", "real-time"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://finnhub.io/api/v1".into() }),
        ("twelve_data", "Twelve Data API", "Technical indicators, historical data — 800+ API calls/day free", "market-info",
         vec!["data", "twelve-data", "free", "indicators"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.twelvedata.com".into() }),
        ("tiingo", "Tiingo API", "Stocks, crypto, forex — IEX-sourced, free tier", "market-info",
         vec!["data", "tiingo", "free", "iex"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.tiingo.com/tiingo/daily".into() }),
        ("fmp", "Financial Modeling Prep", "Financial statements, ratios, DCF — free tier 250 calls/day", "market-info",
         vec!["data", "fmp", "fundamentals", "financial-statements"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://financialmodelingprep.com/api/v3".into() }),
        ("yahoo_finance", "Yahoo Finance (unofficial)", "Free stocks, ETFs, options data — no API key needed", "market-info",
         vec!["data", "yahoo", "free", "stocks"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://query1.finance.yahoo.com/v8".into() }),

        // ── Sentiment & Social ───────────────────────────────────────
        ("cryptopanic", "CryptoPanic API", "Aggregated crypto news — sentiment scores per article", "sentiment",
         vec!["sentiment", "cryptopanic", "news", "crypto"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://cryptopanic.com/api/v1".into() }),
        ("alternative_fg", "Alternative.me Fear & Greed Index", "Crypto Fear & Greed Index — no API key needed", "sentiment",
         vec!["sentiment", "fear-greed", "free", "no-auth"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.alternative.me/fng/".into() }),
        ("lunarcrush", "LunarCrush API", "Social media metrics — Galaxy Score, AltRank, social volume", "sentiment",
         vec!["sentiment", "lunarcrush", "social", "crypto"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://lunarcrush.com/api/v4".into() }),
        ("santiment", "Santiment API", "On-chain + social analytics — Dev Activity, MVRV, NVT, social dominance", "sentiment",
         vec!["sentiment", "santiment", "on-chain", "social"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.santiment.net/graphql".into() }),
        ("thetie", "The TIE API", "Institutional-grade sentiment — crypto and equity sentiment scores", "sentiment",
         vec!["sentiment", "thetie", "institutional", "crypto"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.thetie.io/v1".into() }),
        ("fear_greed_us", "CNN Fear & Greed Index", "US market sentiment — 7 indicators combined", "sentiment",
         vec!["sentiment", "fear-greed", "us-market", "cnn"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://production.dataviz.cnn.io/index/fearandgreed/graphdata".into() }),
        ("redditoauth", "Reddit API", "Subreddit data — wallstreetbets, cryptocurrency, investing", "social",
         vec!["social", "reddit", "community", "free"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://oauth.reddit.com".into() }),

        // ── On-Chain Data ────────────────────────────────────────────
        ("glassnode", "Glassnode API", "On-chain metrics — MVRV, SOPR, exchange flows, hash rate, whale wallets", "onchain",
         vec!["onchain", "glassnode", "metrics", "institutional"], Complexity::Advanced,
         Implementation::HttpEndpoint { url: "https://api.glassnode.com/v1/metrics".into() }),
        ("defillama", "DefiLlama API", "DeFi TVL, yields, protocols — free, unlimited", "onchain",
         vec!["onchain", "defillama", "defi", "free"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.llama.fi".into() }),
        ("dune", "Dune Analytics API", "Custom on-chain queries — community dashboards, SQL-based", "onchain",
         vec!["onchain", "dune", "sql", "custom"], Complexity::Advanced,
         Implementation::HttpEndpoint { url: "https://api.dune.com/api/v1".into() }),
        ("nansen", "Nansen API", "Smart money tracking — wallet labels, fund flows, token god mode", "onchain",
         vec!["onchain", "nansen", "smart-money", "labels"], Complexity::Expert,
         Implementation::HttpEndpoint { url: "https://api.nansen.ai/v1".into() }),
        ("whale_alert", "Whale Alert API", "Large transaction monitoring — exchange inflows/outflows, whale movements", "onchain",
         vec!["onchain", "whale-alert", "transactions", "real-time"], Complexity::Intermediate,
         Implementation::WebSocket { url: "https://api.whale-alert.io/v1".into() }),
        ("cryptoquant", "CryptoQuant API", "On-chain data — exchange reserves, miner flows, funding rates", "onchain",
         vec!["onchain", "cryptoquant", "exchange", "miner"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.cryptoquant.com/v1".into() }),
        ("blockchain_com", "Blockchain.com API", "BTC blockchain data — hash rate, difficulty, mempool, blocks", "onchain",
         vec!["onchain", "blockchain", "btc", "free"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.blockchain.info".into() }),
        ("etherscan", "Etherscan API", "Ethereum blockchain explorer — contracts, transactions, gas", "onchain",
         vec!["onchain", "etherscan", "ethereum", "free"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.etherscan.io/api".into() }),
        ("solscan", "Solana API (Solscan)", "Solana blockchain explorer — accounts, transactions, tokens", "onchain",
         vec!["onchain", "solscan", "solana", "explorer"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://public-api.solscan.io".into() }),

        // ── GDELT (Global Events) ────────────────────────────────────
        ("gdelt", "GDELT Project", "Global event database — news coverage, sentiment, event tracking", "news",
         vec!["news", "gdelt", "global-events", "free"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.gdeltproject.org/api/v2".into() }),

        // ── Exchange Rate / Macro ────────────────────────────────────
        ("exchangerate", "ExchangeRate API", "Free exchange rates — 160+ currencies, updated daily", "macro",
         vec!["macro", "exchange-rate", "free", "currencies"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.exchangerate-api.com/v4/latest/USD".into() }),
        ("fred", "FRED API", "Federal Reserve Economic Data — GDP, CPI, unemployment, rates", "macro",
         vec!["macro", "fred", "federal-reserve", "economic-data"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.stlouisfed.org/fred/series/observations".into() }),
    ];

    for (id, name, desc, subcat, tags, complexity, impl_) in apis {
        registry.register(ToolEntry {
            id: format!("api_{}", id),
            name: name.to_string(),
            category: Category::DataSource,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: impl_,
        });
    }
}
