use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let models = vec![
        ("kelly", "Kelly Criterion", "f* = (bp−q)/b — maximizes long-run geometric growth rate", "sizing",
         vec!["decision", "kelly", "position-sizing", "growth"], Complexity::Intermediate),
        ("half_kelly", "Half-Kelly", "Fractional Kelly for practical use — reduces variance from estimation error", "sizing",
         vec!["decision", "kelly", "conservative", "sizing"], Complexity::Intermediate),
        ("optimal_f", "Optimal F (Ralph Vince)", "Extension of Kelly for non-binomial payoff distributions", "sizing",
         vec!["decision", "optimal-f", "sizing", "non-binomial"], Complexity::Expert),
        ("anti_martingale", "Anti-Martingale", "Increase bets after wins, decrease after losses — scale in trending winners", "sizing",
         vec!["decision", "anti-martingale", "sizing", "scaling"], Complexity::Basic),
        ("fixed_fractional", "Fixed Fractional", "Risk fixed % of equity per trade — simple, robust default", "sizing",
         vec!["decision", "fixed-fractional", "sizing", "simple"], Complexity::Basic),
        ("fixed_ratio", "Fixed Ratio (Ryan Jones)", "Increase position size after earning fixed dollar amount", "sizing",
         vec!["decision", "fixed-ratio", "sizing", "jones"], Complexity::Intermediate),
        ("var_95", "Value at Risk 95%", "Maximum expected loss at 95% confidence over a period", "risk",
         vec!["decision", "var", "risk", "95-percent"], Complexity::Intermediate),
        ("var_99", "Value at Risk 99%", "Maximum expected loss at 99% confidence over a period", "risk",
         vec!["decision", "var", "risk", "99-percent"], Complexity::Intermediate),
        ("expected_shortfall", "Expected Shortfall (CVaR)", "Average loss beyond VaR threshold — better for fat-tailed distributions", "risk",
         vec!["decision", "cvar", "es", "tail-risk"], Complexity::Advanced),
        ("conditional_var", "Conditional VaR", "Same as Expected Shortfall — mean of losses exceeding VaR", "risk",
         vec!["decision", "cvar", "conditional", "tail-risk"], Complexity::Advanced),
        ("monte_carlo", "Monte Carlo Simulation", "Random scenario generation for path-dependent outcomes — stress-test across 10K paths", "simulation",
         vec!["decision", "monte-carlo", "simulation", "stress-test"], Complexity::Advanced),
        ("bayesian_inference", "Bayesian Inference", "Update probability estimates with new evidence — continuously revise edge estimates", "inference",
         vec!["decision", "bayesian", "inference", "updating"], Complexity::Advanced),
        ("markowitz", "Markowitz Mean-Variance", "Maximize return per unit variance on efficient frontier", "portfolio",
         vec!["decision", "markowitz", "mean-variance", "efficient-frontier"], Complexity::Expert),
        ("black_litterman", "Black-Litterman", "Combine market equilibrium with investor views for portfolio allocation", "portfolio",
         vec!["decision", "black-litterman", "portfolio", "views"], Complexity::Expert),
        ("risk_parity", "Risk Parity", "Equal risk contribution from each asset — Bridgewater All Weather approach", "portfolio",
         vec!["decision", "risk-parity", "portfolio", "all-weather"], Complexity::Advanced),
        ("max_sharpe", "Maximum Sharpe Ratio", "Portfolio allocation that maximizes risk-adjusted return", "portfolio",
         vec!["decision", "max-sharpe", "portfolio", "risk-adjusted"], Complexity::Advanced),
        ("min_variance", "Minimum Variance Portfolio", "Portfolio with lowest possible volatility", "portfolio",
         vec!["decision", "min-variance", "portfolio", "lowest-vol"], Complexity::Advanced),
        ("min_cvar", "Minimum CVaR Portfolio", "Portfolio that minimizes tail risk (expected shortfall)", "portfolio",
         vec!["decision", "min-cvar", "portfolio", "tail-risk"], Complexity::Expert),
        ("hrp", "Hierarchical Risk Parity", "Machine learning approach to portfolio allocation — no matrix inversion needed", "portfolio",
         vec!["decision", "hrp", "portfolio", "machine-learning"], Complexity::Expert),
        ("black_scholes", "Black-Scholes Model", "European option pricing via risk-neutral valuation", "options",
         vec!["decision", "black-scholes", "options", "pricing"], Complexity::Expert),
        ("binomial_model", "Binomial Tree Model", "Discrete-time option pricing — handles American options with early exercise", "options",
         vec!["decision", "binomial", "options", "american"], Complexity::Expert),
        ("monte_carlo_option", "Monte Carlo Option Pricing", "Simulate many price paths for exotic options — path-dependent payoffs", "options",
         vec!["decision", "monte-carlo", "options", "exotic"], Complexity::Expert),
        ("greeks_delta", "Delta Hedging", "Maintain delta-neutral position — dynamic hedging to eliminate directional risk", "hedging",
         vec!["decision", "delta", "hedging", "dynamic"], Complexity::Advanced),
        ("implied_vol_smile", "Implied Volatility Surface", "Map IV across strikes and expirations — detect overpriced/underpriced options", "volatility",
         vec!["decision", "iv-surface", "volatility", "skew"], Complexity::Expert),
        ("var_decomp", "VaR Decomposition", "Break portfolio VaR into component contributions by asset", "risk",
         vec!["decision", "var-decomposition", "component-var", "attribution"], Complexity::Expert),
        ("factor_model", "Factor Model (Fama-French)", "Decompose returns into factor exposures — identify true alpha vs factor beta", "alpha",
         vec!["decision", "factor-model", "fama-french", "alpha"], Complexity::Expert),
        ("regime_detection", "Regime Detection (HMM)", "Hidden Markov Model to identify bull/bear/crisis regimes", "regime",
         vec!["decision", "hmm", "regime", "markov"], Complexity::Expert),
        ("drawdown_control", "Drawdown Control", "Reduce position size proportional to current drawdown — anti-fragile sizing", "risk",
         vec!["decision", "drawdown-control", "anti-fragile", "adaptive"], Complexity::Intermediate),
        ("trailing_stop_atr", "ATR Trailing Stop", "Dynamic stop-loss based on Average True Range — adapts to volatility", "execution",
         vec!["decision", "atr-trailing", "stop-loss", "volatility-adaptive"], Complexity::Basic),
        ("time_stop", "Time-Based Stop", "Exit after N bars regardless of P&L — prevents dead capital", "execution",
         vec!["decision", "time-stop", "capital-preservation", "time-based"], Complexity::Basic),
    ];

    for (id, name, desc, subcat, tags, complexity) in models {
        registry.register(ToolEntry {
            id: format!("decision_{}", id),
            name: name.to_string(),
            category: Category::DecisionModel,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: Implementation::BuiltIn,
        });
    }
}
