use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    // ── Risk Models ──────────────────────────────────────────────────
    let risk_models = vec![
        ("var_historical", "Historical VaR", "Use actual past returns to estimate risk", "var"),
        ("var_parametric", "Parametric VaR", "Assume normal distribution for risk estimation", "var"),
        ("var_monte_carlo", "Monte Carlo VaR", "Simulate paths for non-normal distributions", "var"),
        ("cvar", "Conditional VaR (CVaR)", "Expected shortfall beyond VaR", "var"),
        ("es_parametric", "Expected Shortfall Parametric", "Average loss beyond VaR under normality", "var"),
        ("stress_test_historical", "Historical Stress Test", "Apply past crisis scenarios to current portfolio", "stress"),
        ("stress_test_reverse", "Reverse Stress Test", "Find scenarios that cause target loss level", "stress"),
        ("stress_test_factor", "Factor Stress Test", "Shock individual risk factors and measure impact", "stress"),
        ("stress_test_monte_carlo", "Monte Carlo Stress Test", "Generate extreme but plausible scenarios", "stress"),
        ("scenario_analysis", "Scenario Analysis", "Evaluate portfolio under predefined economic scenarios", "stress"),
        ("drawdown_max", "Maximum Drawdown", "Largest peak-to-trough decline", "drawdown"),
        ("drawdown_calmar", "Calmar Ratio", "Annualized return / max drawdown", "drawdown"),
        ("drawdown_recovery", "Drawdown Recovery Time", "Expected time to recover from current drawdown", "drawdown"),
        ("drawdown_ulcer", "Ulcer Index", "RMS of drawdowns — measures depth and duration", "drawdown"),
        ("drawdown_pain", "Pain Index", "Average drawdown magnitude over period", "drawdown"),
        ("correlation_pearson", "Pearson Correlation", "Linear correlation between assets", "correlation"),
        ("correlation_spearman", "Spearman Rank Correlation", "Non-parametric rank-based correlation", "correlation"),
        ("correlation_kendall", "Kendall Tau Correlation", "Ordinal association measure", "correlation"),
        ("correlation_distance", "Distance Correlation", "Detects non-linear dependencies", "correlation"),
        ("tail_ratio", "Tail Ratio", "Right tail / left tail ratio — asymmetry of returns", "tail"),
        ("skewness", "Return Skewness", "Asymmetry of return distribution — negative = crash risk", "tail"),
        ("kurtosis", "Return Kurtosis", "Tail heaviness — excess kurtosis > 3 = fat tails", "tail"),
        ("jarque_bera", "Jarque-Bera Test", "Normality test for return distribution", "tail"),
        ("max_loss", "Maximum Single Loss", "Largest single-period loss in the sample", "loss"),
        ("expectancy", "Trade Expectancy", "Average P&L per trade — must be positive for edge", "expectancy"),
        ("profit_factor", "Profit Factor", "Gross profits / gross losses — ratio of winning to losing", "expectancy"),
        ("payoff_ratio", "Payoff Ratio", "Average win / average loss", "expectancy"),
        ("edge_ratio", "Edge Ratio", "Ratio of time in profit vs time in loss", "expectancy"),
        ("kelly_full", "Full Kelly Fraction", "Optimal bet fraction from win rate and payoff ratio", "sizing"),
        ("kelly_half", "Half Kelly Fraction", "Conservative sizing — reduces variance from estimation error", "sizing"),
        ("kelly_quarter", "Quarter Kelly Fraction", "Ultra-conservative sizing for uncertain estimates", "sizing"),
        ("optimal_f_ralph", "Optimal F (Ralph Vince)", "Maximum f from actual trade distribution", "sizing"),
        ("position_size_fixed", "Fixed Position Size", "Constant dollar amount per trade", "sizing"),
        ("position_size_percent", "Fixed Percent Risk", "Risk fixed % of equity per trade", "sizing"),
        ("position_size_volatility", "Volatility-Adjusted Sizing", "Position inversely proportional to ATR", "sizing"),
        ("position_size_kelly", "Kelly Position Sizing", "Position size from Kelly Criterion", "sizing"),
        ("position_size_target_heat", "Target Heat Sizing", "Risk a fixed % of total portfolio heat", "sizing"),
        ("risk_of_ruin", "Risk of Ruin", "Probability of hitting stop-loss before reaching target", "ruin"),
        ("risk_of_ruin_sim", "Risk of Ruin (Simulation)", "Monte Carlo based risk of ruin estimate", "ruin"),
        ("sequence_of_returns", "Sequence of Returns Risk", "Impact of return ordering on portfolio outcomes", "sequence"),
        ("rebalancing_optimal", "Optimal Rebalancing", "Minimize tracking error vs target allocation", "rebalance"),
        ("rebalancing_calendar", "Calendar Rebalancing", "Rebalance at fixed time intervals", "rebalance"),
        ("rebalancing_threshold", "Threshold Rebalancing", "Rebalance when drift exceeds threshold", "rebalance"),
    ];

    for (id, name, desc, subcat) in risk_models {
        registry.register(ToolEntry {
            id: format!("risk_{}", id),
            name: name.to_string(),
            category: Category::RiskModel,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["risk".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Execution Algorithms ─────────────────────────────────────────
    let execution = vec![
        ("twap", "Time-Weighted Average Price", "Execute evenly over time window", "algo"),
        ("vwap", "Volume-Weighted Average Price", "Execute proportional to volume profile", "algo"),
        ("is", "Implementation Shortfall", "Minimize difference between decision and execution price", "algo"),
        ("pov", "Percentage of Volume", "Participate at fixed % of market volume", "algo"),
        ("iceberg", "Iceberg Order", "Show small size, resupply from hidden reserve", "algo"),
        ("sniper", "Sniper Order", "Aggressive fill-seeking with price improvement", "algo"),
        ("dark_ice", "Dark Ice", "Undisclosed order in dark pool", "algo"),
        ("arrival_price", "Arrival Price Algorithm", "Minimize slippage vs arrival price", "algo"),
        ("moc", "Market-on-Close", "Execute at closing auction", "algo"),
        ("loc", "Limit-on-Close", "Limit order at closing price", "algo"),
        ("pov_target", "POV Target", "Reach target participation rate", "algo"),
        ("spread_capture", "Spread Capture", "Place bids and offers to capture bid-ask spread", "algo"),
        ("peg_mid", "Peg to Midpoint", "Order pegged to midpoint of NBBO", "algo"),
        ("peg_primary", "Peg to Primary", "Order pegged to primary exchange quote", "algo"),
        ("sweep_iceberg", "Sweep Iceberg", "Detect and sweep iceberg order liquidity", "algo"),
        ("smart_router", "Smart Order Router", "Route to best venue based on price/size/fee", "algo"),
        ("cross_market", "Cross-Market Execution", "Execute across multiple venues simultaneously", "algo"),
        ("bait_order", "Bait Order", "Place small order to detect hidden liquidity", "algo"),
        ("fade_order", "Fade Order", "Trade against momentum when exhaustion detected", "algo"),
        ("cancel_replace", "Cancel-Replace", "Iteratively improve order price", "algo"),
        ("bracket", "Bracket Order", "Entry with linked stop-loss and take-profit", "algo"),
        ("oco", "One-Cancels-Other", "Two orders where filling one cancels the other", "algo"),
        ("trailing_stop_pct", "Percentage Trailing Stop", "Stop follows price at fixed % distance", "algo"),
        ("trailing_stop_atr", "ATR Trailing Stop", "Stop follows price based on ATR multiple", "algo"),
        ("trailing_stop_chandelier", "Chandelier Exit", "Trailing stop at highest high minus ATR multiple", "algo"),
        ("time_stop", "Time-Based Stop", "Exit after N bars if not at target", "algo"),
        ("volatility_breakout", "Volatility Breakout", "Enter when price moves N*ATR from open", "algo"),
        ("gap_fill", "Gap Fill Order", "Enter expecting gap to fill, target previous close", "algo"),
        ("scale_in", "Scale-In Order", "Enter position in multiple tranches", "algo"),
        ("scale_out", "Scale-Out Order", "Exit position in multiple tranches", "algo"),
    ];

    for (id, name, desc, subcat) in execution {
        registry.register(ToolEntry {
            id: format!("exec_{}", id),
            name: name.to_string(),
            category: Category::ExecutionAlgo,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["execution".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── ML/AI Models ─────────────────────────────────────────────────
    let ml_models = vec![
        ("linear_regression", "Linear Regression", "Predict returns from features", "supervised"),
        ("logistic_regression", "Logistic Regression", "Classify trade direction", "supervised"),
        ("random_forest", "Random Forest", "Ensemble of decision trees", "supervised"),
        ("gradient_boosting", "Gradient Boosting (XGBoost/LightGBM)", "Boosted tree ensemble", "supervised"),
        ("svm", "Support Vector Machine", "Margin-based classification", "supervised"),
        ("neural_network", "Neural Network (MLP)", "Deep feedforward network", "deep"),
        ("lstm", "LSTM Network", "Sequential pattern recognition", "deep"),
        ("transformer", "Transformer Model", "Attention-based sequence model", "deep"),
        ("cnn", "CNN for Time Series", "Pattern recognition in price charts", "deep"),
        ("autoencoder", "Autoencoder", "Anomaly detection via reconstruction", "unsupervised"),
        ("kmeans", "K-Means Clustering", "Regime detection via clustering", "unsupervised"),
        ("dbscan", "DBSCAN", "Density-based regime clustering", "unsupervised"),
        ("pca", "Principal Component Analysis", "Dimensionality reduction for factor models", "unsupervised"),
        ("gmm", "Gaussian Mixture Model", "Probabilistic regime classification", "unsupervised"),
        ("hmm", "Hidden Markov Model", "Sequential regime detection", "sequential"),
        ("kalman_filter", "Kalman Filter", "Optimal state estimation — noise filtering", "sequential"),
        ("particle_filter", "Particle Filter", "Non-linear state estimation", "sequential"),
        ("q_learning", "Q-Learning", "Tabular reinforcement learning", "rl"),
        ("dqn", "Deep Q-Network", "Neural network RL agent", "rl"),
        ("ppo", "Proximal Policy Optimization", "Policy gradient RL", "rl"),
        ("a2c", "Advantage Actor-Critic", "Actor-critic RL algorithm", "rl"),
        ("sac", "Soft Actor-Critic", "Entropy-regularized RL", "rl"),
        ("bayesian_nn", "Bayesian Neural Network", "Uncertainty-aware deep learning", "bayesian"),
        ("gaussian_process", "Gaussian Process", "Non-parametric regression with uncertainty", "bayesian"),
        ("ensemble_voting", "Ensemble Voting", "Majority vote from multiple models", "ensemble"),
        ("ensemble_stacking", "Stacked Ensemble", "Meta-learner on top of base models", "ensemble"),
        ("ensemble_blending", "Blended Ensemble", "Weighted average of model predictions", "ensemble"),
        ("online_adaptive", "Online Adaptive Model", "Continuously retrain on new data", "online"),
        ("meta_learner", "Meta-Learner", "Learn to combine model predictions", "meta"),
        ("anomaly_detector", "Anomaly Detector", "Flag unusual market conditions", "anomaly"),
    ];

    for (id, name, desc, subcat) in ml_models {
        registry.register(ToolEntry {
            id: format!("ml_{}", id),
            name: name.to_string(),
            category: Category::MLModel,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Advanced,
            tags: vec!["ml".into(), "model".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Backtest Methods ─────────────────────────────────────────────
    let backtest = vec![
        ("event_driven", "Event-Driven Backtest", "Simulate real market events", "method"),
        ("vectorized", "Vectorized Backtest", "Matrix operations for speed", "method"),
        ("agent_based", "Agent-Based Simulation", "Model individual market participants", "method"),
        ("walk_forward", "Walk-Forward Analysis", "Rolling train/test split", "validation"),
        ("monte_carlo_sim", "Monte Carlo Backtest", "Random market path generation", "validation"),
        ("bootstrap", "Bootstrap Resampling", "Resample historical returns", "validation"),
        ("cross_validation", "K-Fold Cross Validation", "Partition data into K train/test folds", "validation"),
        ("purged_cv", "Purged Cross Validation", "Remove overlap between train/test", "validation"),
        ("combinatorial_cv", "Combinatorial CV", "All possible train/test combinations", "validation"),
        ("deflated_sharpe", "Deflated Sharpe Ratio", "Adjust Sharpe for multiple testing", "validation"),
        ("minimum_backtest_length", "Minimum Backtest Length", "Required sample size for significance", "validation"),
        ("out_of_sample", "Out-of-Sample Test", "Validate on unseen data", "validation"),
        ("paper_trading", "Paper Trading", "Live market with fake money", "validation"),
        ("slippage_model_fixed", "Fixed Slippage Model", "Constant slippage per trade", "cost"),
        ("slippage_model_volume", "Volume-Proportional Slippage", "Slippage proportional to trade size", "cost"),
        ("slippage_model_impact", "Market Impact Model", "Slippage from price impact", "cost"),
        ("commission_model_fixed", "Fixed Commission", "Constant fee per trade", "cost"),
        ("commission_model_percent", "Percentage Commission", "Fee as % of trade value", "cost"),
        ("commission_model_tiered", "Tiered Commission", "Volume-based fee schedule", "cost"),
        ("latency_model", "Latency Model", "Account for execution delay", "cost"),
    ];

    for (id, name, desc, subcat) in backtest {
        registry.register(ToolEntry {
            id: format!("backtest_{}", id),
            name: name.to_string(),
            category: Category::BacktestMethod,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["backtest".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Order Types ──────────────────────────────────────────────────
    let orders = vec![
        ("market", "Market Order", "Execute at best available price", "basic"),
        ("limit", "Limit Order", "Execute at specified price or better", "basic"),
        ("stop", "Stop Order", "Trigger market order when price reached", "basic"),
        ("stop_limit", "Stop-Limit Order", "Trigger limit order when stop reached", "basic"),
        ("trailing_stop", "Trailing Stop", "Stop that follows price by fixed amount", "basic"),
        ("trailing_stop_pct", "Trailing Stop %", "Stop that follows price by percentage", "basic"),
        ("iceberg", "Iceberg Order", "Hidden quantity order", "advanced"),
        ("tif_day", "Day Order (TIF)", "Expires at end of trading day", "tif"),
        ("tif_gtc", "Good-Til-Cancel (GTC)", "Stays active until filled or cancelled", "tif"),
        ("tif_ioc", "Immediate-or-Cancel (IOC)", "Fill what you can immediately, cancel rest", "tif"),
        ("tif_fok", "Fill-or-Kill (FOK)", "Fill entire order immediately or cancel all", "tif"),
        ("tif_gtd", "Good-Til-Date (GTD)", "Expires at specified date/time", "tif"),
        ("tif_atc", "At-the-Close", "Execute at market close", "tif"),
        ("tif_ato", "At-the-Open", "Execute at market open", "tif"),
        ("bracket", "Bracket Order", "Entry + linked stop + target", "complex"),
        ("oco", "One-Cancels-Other", "Two orders, one cancels on fill", "complex"),
        ("oto", "One-Triggers-Other", "Entry triggers stop/target placement", "complex"),
        ("oto_bracket", "One-Triggers-Bracket", "Entry triggers bracket order", "complex"),
        ("trailing_bracket", "Trailing Bracket", "Bracket with trailing stop", "complex"),
        ("scale", "Scale Order", "Multiple limit orders at different prices", "complex"),
        ("sor", "Smart Order Router", "Auto-route to best venue", "smart"),
        ("pegged", "Pegged Order", "Pegged to NBBO midpoint/primary", "smart"),
        ("reserve", "Reserve Order", "Display partial, hide rest", "smart"),
        ("midpoint_disclose", "Midpoint-Displaced Limit", "Limit order at midpoint + offset", "smart"),
    ];

    for (id, name, desc, subcat) in orders {
        registry.register(ToolEntry {
            id: format!("order_{}", id),
            name: name.to_string(),
            category: Category::OrderType,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Basic,
            tags: vec!["order".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Risk Metrics ─────────────────────────────────────────────────
    let metrics = vec![
        ("sharpe", "Sharpe Ratio", "Risk-adjusted return vs risk-free rate"),
        ("sortino", "Sortino Ratio", "Downside deviation-adjusted return"),
        ("treynor", "Treynor Ratio", "Return per unit of systematic risk"),
        ("information_ratio", "Information Ratio", "Active return / tracking error"),
        ("modigliani", "Modigliani Ratio (M2)", "Risk-adjusted return normalized to market volatility"),
        ("omega", "Omega Ratio", "Probability-weighted gains/losses above threshold"),
        ("kappa", "Kappa Ratio", "Higher-moment risk-adjusted return"),
        ("calmar", "Calmar Ratio", "Annualized return / max drawdown"),
        ("sterling", "Sterling Ratio", "Annualized return / average max drawdown"),
        ("burke", "Burke Ratio", "Return / downside deviation of drawdowns"),
        ("mar", "MAR Ratio", "CAGR / max drawdown"),
        ("tail_loss", "Tail Loss Ratio", "Average loss in worst X% of returns"),
        ("ulcer_index", "Ulcer Index", "RMS of drawdown percentages"),
        ("recovery_factor", "Recovery Factor", "Net profit / max drawdown"),
        ("payoff_ratio", "Payoff Ratio", "Average winning trade / average losing trade"),
        ("win_rate", "Win Rate", "% of trades that are profitable"),
        ("expectancy_r", "Expectancy R", "Average R-multiple per trade"),
        ("system_quality", "System Quality Number (SQN)", "Sharpe-like measure for trade distribution"),
        ("gains_to_pain", "Gains-to-Pain Ratio", "Sum of gains / sum of drawdown pain"),
        ("lake_ratio", "Lake Ratio", "Sum of drawdowns / sum of gains"),
        ("common_sense_ratio", "Common Sense Ratio", "Payoff ratio * win rate"),
        ("cpc_index", "CPC Index", "Expectancy * profit factor"),
        ("r_squared", "R-Squared", "Linearity of equity curve"),
        ("autocorrelation", "Return Autocorrelation", "Serial correlation in returns"),
        ("max_consecutive_loss", "Max Consecutive Losses", "Worst losing streak"),
        ("avg_bars_in_trade", "Average Bars in Trade", "Duration of average position"),
        ("avg_bars_in_drawdown", "Average Bars in Drawdown", "Duration of average drawdown period"),
        ("turnover_rate", "Turnover Rate", "How frequently portfolio changes"),
    ];

    for (id, name, desc) in metrics {
        registry.register(ToolEntry {
            id: format!("metric_{}", id),
            name: name.to_string(),
            category: Category::RiskMetric,
            description: desc.to_string(),
            subcategory: "performance".to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["metric".into(), "performance".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Timeframes ───────────────────────────────────────────────────
    let timeframes = vec![
        ("1m", "1 Minute", "Ultra-short-term scalping"),
        ("3m", "3 Minutes", "Scalping and HFT"),
        ("5m", "5 Minutes", "Intraday scalping"),
        ("15m", "15 Minutes", "Intraday short-term"),
        ("30m", "30 Minutes", "Intraday medium-term"),
        ("1h", "1 Hour", "Intraday and swing entry"),
        ("2h", "2 Hours", "Swing confirmation"),
        ("4h", "4 Hours", "Swing trading primary"),
        ("1d", "1 Day", "Daily swing and position"),
        ("1w", "1 Week", "Weekly position trading"),
        ("1M", "1 Month", "Monthly macro positioning"),
        ("3M", "3 Months", "Quarterly macro"),
        ("1Y", "1 Year", "Annual macro allocation"),
    ];

    for (id, name, desc) in timeframes {
        registry.register(ToolEntry {
            id: format!("tf_{}", id),
            name: name.to_string(),
            category: Category::TimeFrame,
            description: desc.to_string(),
            subcategory: "period".to_string(),
            complexity: Complexity::Basic,
            tags: vec!["timeframe".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Chart Patterns ───────────────────────────────────────────────
    let patterns = vec![
        ("head_shoulders", "Head & Shoulders", "Three-peak pattern with neckline break", "reversal"),
        ("head_shoulders_inv", "Inverse Head & Shoulders", "Bullish reversal pattern", "reversal"),
        ("double_top", "Double Top", "Two equal highs with neckline break", "reversal"),
        ("double_bottom", "Double Bottom", "Two equal lows with neckline break", "reversal"),
        ("triple_top", "Triple Top", "Three equal highs — strong resistance", "reversal"),
        ("triple_bottom", "Triple Bottom", "Three equal lows — strong support", "reversal"),
        ("cup_handle", "Cup & Handle", "Rounded bottom with small pullback", "continuation"),
        ("rounding_bottom", "Rounding Bottom", "Gradual shift from bearish to bullish", "reversal"),
        ("rounding_top", "Rounding Top", "Gradual shift from bullish to bearish", "reversal"),
        ("ascending_triangle", "Ascending Triangle", "Flat top + rising bottom — bullish breakout", "continuation"),
        ("descending_triangle", "Descending Triangle", "Flat bottom + falling top — bearish breakout", "continuation"),
        ("symmetrical_triangle", "Symmetrical Triangle", "Converging trendlines — direction TBD", "consolidation"),
        ("bull_flag", "Bull Flag", "Sharp rise + slight downward channel — bullish continuation", "continuation"),
        ("bear_flag", "Bear Flag", "Sharp drop + slight upward channel — bearish continuation", "continuation"),
        ("bull_pennant", "Bull Pennant", "Sharp rise + converging consolidation — bullish", "continuation"),
        ("bear_pennant", "Bear Pennant", "Sharp drop + converging consolidation — bearish", "continuation"),
        ("wedge_falling", "Falling Wedge", "Converging downward — bullish breakout expected", "reversal"),
        ("wedge_rising", "Rising Wedge", "Converging upward — bearish breakdown expected", "reversal"),
        ("broadening", "Broadening Formation", "Diverging trendlines — increasing volatility", "consolidation"),
        ("diamond_top", "Diamond Top", "Reversal pattern at market tops", "reversal"),
        ("diamond_bottom", "Diamond Bottom", "Reversal pattern at market bottoms", "reversal"),
        ("v_bottom", "V-Bottom", "Sharp reversal — capitulation and recovery", "reversal"),
        ("v_top", "V-Top", "Sharp reversal at top — blow-off and crash", "reversal"),
        ("rectangle", "Rectangle / Trading Range", "Horizontal support and resistance", "consolidation"),
        ("channel_up", "Ascending Channel", "Higher highs and higher lows in parallel", "trend"),
        ("channel_down", "Descending Channel", "Lower highs and lower lows in parallel", "trend"),
        ("channel_horizontal", "Horizontal Channel", "Sideways price action in range", "range"),
        ("gap_up", "Gap Up", "Price gaps above previous range — breakout", "breakout"),
        ("gap_down", "Gap Down", "Price gaps below previous range — breakdown", "breakdown"),
        ("island_reversal", "Island Reversal", "Gap in both directions — reversal signal", "reversal"),
        ("marubozu_bull", "Bullish Marubozu", "Strong bullish candle — no wicks, full conviction", "candle"),
        ("marubozu_bear", "Bearish Marubozu", "Strong bearish candle — no wicks, full conviction", "candle"),
        ("doji", "Doji", "Indecision candle — open ≈ close", "candle"),
        ("hammer", "Hammer", "Bullish reversal — long lower wick at bottom", "candle"),
        ("hanging_man", "Hanging Man", "Bearish reversal — long lower wick at top", "candle"),
        ("shooting_star", "Shooting Star", "Bearish reversal — long upper wick at top", "candle"),
        ("engulfing_bull", "Bullish Engulfing", "Green candle fully engulfs previous red", "candle"),
        ("engulfing_bear", "Bearish Engulfing", "Red candle fully engulfs previous green", "candle"),
        ("morning_star", "Morning Star", "Three-candle bullish reversal pattern", "candle"),
        ("evening_star", "Evening Star", "Three-candle bearish reversal pattern", "candle"),
        ("three_white_soldiers", "Three White Soldiers", "Three consecutive bullish candles — strong uptrend", "candle"),
        ("three_black_crows", "Three Black Crows", "Three consecutive bearish candles — strong downtrend", "candle"),
        ("harami_bull", "Bullish Harami", "Small green candle inside previous large red", "candle"),
        ("harami_bear", "Bearish Harami", "Small red candle inside previous large green", "candle"),
        ("piercing_line", "Piercing Line", "Bullish two-candle reversal at support", "candle"),
        ("dark_cloud", "Dark Cloud Cover", "Bearish two-candle reversal at resistance", "candle"),
        ("tweezer_top", "Tweezer Top", "Two candles with matching highs — resistance", "candle"),
        ("tweezer_bottom", "Tweezer Bottom", "Two candles with matching lows — support", "candle"),
        ("spinning_top", "Spinning Top", "Small body with equal wicks — indecision", "candle"),
    ];

    for (id, name, desc, subcat) in patterns {
        registry.register(ToolEntry {
            id: format!("pattern_{}", id),
            name: name.to_string(),
            category: Category::PatternType,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["pattern".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Regime Types ─────────────────────────────────────────────────
    let regimes = vec![
        ("trending_bull", "Trending Bull", "Sustained upward price movement with higher highs/lows"),
        ("trending_bear", "Trending Bear", "Sustained downward price movement with lower highs/lows"),
        ("ranging", "Ranging / Sideways", "Price oscillates between support and resistance"),
        ("volatile", "High Volatility", "Wide price swings — ATR elevated above average"),
        ("low_volatility", "Low Volatility", "Compressed range — potential breakout building"),
        ("breakout", "Breakout", "Price breaks out of consolidation with volume"),
        ("breakdown", "Breakdown", "Price breaks below support with volume"),
        ("mean_reversion", "Mean Reversion", "Price overshoots fair value and reverts"),
        ("momentum", "Strong Momentum", "Trending with acceleration — increasing momentum"),
        ("exhaustion", "Exhaustion", "Trend losing momentum — reversal approaching"),
        ("capitulation", "Capitulation", "Panic selling — extreme fear, volume spike"),
        ("euphoria", "Euphoria", "Extreme optimism — potential market top"),
        ("accumulation", "Accumulation", "Smart money buying at support — stealth phase"),
        ("distribution", "Distribution", "Smart money selling at resistance — stealth phase"),
        ("news_driven", "News-Driven", "Price moves dominated by news catalyst"),
        ("algorithmic", "Algorithmic / HFT", "Price action dominated by algorithmic trading"),
        ("thin_liquidity", "Thin Liquidity", "Low volume, wide spreads — fragile market"),
        ("crisis", "Crisis / Black Swan", "Extreme tail event — correlation goes to 1"),
    ];

    for (id, name, desc) in regimes {
        registry.register(ToolEntry {
            id: format!("regime_{}", id),
            name: name.to_string(),
            category: Category::RegimeType,
            description: desc.to_string(),
            subcategory: "classification".to_string(),
            complexity: Complexity::Advanced,
            tags: vec!["regime".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Additional Data Sources ──────────────────────────────────────
    let extra_apis = vec![
        ("binance_klines", "Binance Klines API", "Candlestick data", "kline"),
        ("binance_depth", "Binance Order Book", "L2 order book depth", "depth"),
        ("binance_trades", "Binance Recent Trades", "Recent trade history", "trades"),
        ("binance_funding", "Binance Funding Rate", "Perpetual funding rate", "funding"),
        ("binance_open_interest", "Binance Open Interest", "Futures open interest", "derivatives"),
        ("binance_long_short", "Binance Long/Short Ratio", "Account-level long/short ratio", "derivatives"),
        ("binance_ticker", "Binance Ticker 24h", "24h price/volume statistics", "market"),
        ("coingecko_markets", "CoinGecko Markets", "Top coins by market cap", "market"),
        ("coingecko_ohlcv", "CoinGecko OHLCV", "Historical price data", "price"),
        ("coingecko_global", "CoinGecko Global", "Global crypto market stats", "market"),
        ("defillama_protocols", "DefiLlama Protocols", "All DeFi protocol TVL", "defi"),
        ("defillama_yields", "DefiLlama Yields", "Yield farming rates across protocols", "defi"),
        ("defillama_stablecoins", "DefiLlama Stablecoins", "Stablecoin market cap and flows", "defi"),
        ("defillama_dex", "DefiLlama DEX Volume", "DEX trading volume", "defi"),
        ("blockstream_esplora", "Blockstream Esplora", "BTC blockchain explorer API", "btc"),
        ("blockchain_mempool", "Blockchain.com Mempool", "Unconfirmed transactions", "btc"),
        ("ethereum_beacon", "Ethereum Beacon Chain", "Validator and staking data", "eth"),
        ("polygon_scan", "PolygonScan API", "Polygon blockchain explorer", "matic"),
        ("arbiscan", "Arbiscan API", "Arbitrum blockchain explorer", "arb"),
        ("optimism_scan", "Optimism Etherscan", "Optimism blockchain explorer", "op"),
        ("base_scan", "Basescan API", "Base blockchain explorer", "base"),
        ("solana_rpc", "Solana RPC API", "Solana blockchain direct RPC", "sol"),
        ("avalanche_snowtrace", "Snowtrace API", "Avalanche blockchain explorer", "avax"),
        ("bscscan", "BscScan API", "BNB Chain blockchain explorer", "bnb"),
        ("coinalpha", "Coin Alpha API", "Crypto market data aggregator", "market"),
        ("nomics", "Nomics API", "Crypto market data — clean, institutional", "market"),
        ("coinmarketcap", "CoinMarketCap API", "Crypto prices and rankings", "market"),
        ("tradingview_ws", "TradingView WebSocket", "Real-time charting data", "chart"),
        ("cryptocompare", "CryptoCompare API", "Crypto historical and real-time data", "market"),
        ("blockchair", "Blockchair API", "Multi-chain blockchain explorer", "chain"),
    ];

    for (id, name, desc, subcat) in extra_apis {
        registry.register(ToolEntry {
            id: format!("xapi_{}", id),
            name: name.to_string(),
            category: Category::DataSource,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Basic,
            tags: vec!["data".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Portfolio Methods ────────────────────────────────────────────
    let portfolio_methods = vec![
        ("mean_variance", "Mean-Variance Optimization", "Classic Markowitz — max return per unit risk"),
        ("min_variance", "Minimum Variance", "Lowest possible portfolio volatility"),
        ("max_sharpe", "Maximum Sharpe", "Optimal risk-adjusted allocation"),
        ("risk_parity", "Risk Parity", "Equal risk contribution per asset"),
        ("equal_weight", "Equal Weight", "Simple 1/N allocation"),
        ("market_cap_weight", "Market Cap Weighted", "Benchmark-weighted allocation"),
        ("fundamental_weight", "Fundamental Weighted", "Weight by revenue/earnings/book"),
        ("hrp", "Hierarchical Risk Parity", "Tree-based allocation without matrix inversion"),
        ("black_litterman", "Black-Litterman", "Combine equilibrium with investor views"),
        ("max_diversification", "Maximum Diversification", "Maximize diversification ratio"),
        ("min_cvar", "Minimum CVaR", "Minimize tail risk"),
        ("cvar_optimization", "CVaR Optimization", "Optimize for expected shortfall"),
        ("shrinkage_estimation", "Shrinkage Estimation", "Ledoit-Wolf covariance shrinkage"),
        ("dccc", "Dynamic Conditional Correlation", "Time-varying correlation for allocation"),
        ("factor_portfolio", "Factor Portfolio", "Allocation by factor exposures"),
        ("smart_beta", "Smart Beta", "Rules-based factor exposure"),
        ("volatility_targeting", "Volatility Targeting", "Scale exposure to maintain target vol"),
        ("trend_following", "Trend-Following Allocation", "Time-series momentum allocation"),
        ("carry_trade", "Carry Trade", "Earn yield differential between assets"),
        ("asset_momentum", "Asset Momentum", "Cross-sectional momentum allocation"),
    ];

    for (id, name, desc) in portfolio_methods {
        registry.register(ToolEntry {
            id: format!("portfolio_{}", id),
            name: name.to_string(),
            category: Category::PortfolioMethod,
            description: desc.to_string(),
            subcategory: "allocation".to_string(),
            complexity: Complexity::Advanced,
            tags: vec!["portfolio".into(), "allocation".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Additional Skills ────────────────────────────────────────────
    let extra_skills = vec![
        ("market_microstructure", "Market Microstructure Analysis", "Order book dynamics, bid-ask, informed trading", "analysis"),
        ("cross_asset_correlation", "Cross-Asset Correlation Monitor", "Track correlation regime changes across asset classes", "analysis"),
        ("regime_switching_model", "Regime-Switching Model", "Statistical model for market state transitions", "analysis"),
        ("calendar_effects", "Calendar Effects Analysis", "January effect, Monday effect, OPEX cycles", "analysis"),
        ("sector_rotation", "Sector Rotation Model", "Rotate equity sectors based on business cycle", "strategy"),
        ("pairs_screener", "Pairs Screener", "Find cointegrated pairs for pairs trading", "strategy"),
        ("earnings_surprise", "Earnings Surprise Detector", "Real-time earnings beat/miss detection", "analysis"),
        ("insider_flow", "Insider Trading Flow", "Aggregate insider buying/selling patterns", "analysis"),
        ("institutional_flow", "Institutional Fund Flow", "Track large fund allocation changes", "analysis"),
        ("dark_pool_prints", "Dark Pool Transaction Prints", "Detect large off-exchange trades", "analysis"),
        ("options_unusual_activity", "Unusual Options Activity", "Detect unusual options volume spikes", "analysis"),
        ("gamma_exposure", "Dealer Gamma Exposure", "Estimate dealer hedging flows from options positioning", "analysis"),
        ("vanna_flows", "Vanna Charm Flows", "Options-driven delta hedging flows", "analysis"),
        ("vol_surface_skew", "Volatility Surface Skew", "Measure put/call vol skew for sentiment", "analysis"),
        ("term_structure_slope", "Term Structure Analysis", "Futures contango/backwardation signals", "analysis"),
        ("cross_exchange_basis", "Cross-Exchange Basis", "Futures-spot basis across exchanges", "analysis"),
        ("stablecoin_depeg", "Stablecoin De-Peg Monitor", "Track stablecoin deviations from peg", "analysis"),
        ("nft_floor_price", "NFT Floor Price Tracker", "NFT market sentiment via floor prices", "analysis"),
        ("dao_governance", "DAO Governance Tracker", "Track governance proposals and voting", "analysis"),
        ("smart_contract_audit", "Smart Contract Risk Scoring", "Audit score for DeFi protocol safety", "analysis"),
        ("gas_optimization", "Gas Optimization Timing", "Find lowest gas periods for on-chain execution", "execution"),
        ("mev_protection", "MEV Protection", "Protect against sandwich attacks and front-running", "execution"),
        ("flash_loan_detector", "Flash Loan Detector", "Detect flash loan-based attacks or arbitrage", "analysis"),
        ("whale_wallet_tracker", "Whale Wallet Tracker", "Monitor known large wallet movements", "analysis"),
        ("exchange_withdrawal", "Exchange Withdrawal Monitor", "Track large BTC/ETH withdrawals from exchanges", "analysis"),
        ("mining_hashrate", "Mining Hashrate Monitor", "Network security and miner health indicator", "analysis"),
        ("network_congestion", "Network Congestion Monitor", "Mempool size, gas prices, fee estimation", "analysis"),
        ("regulatory_tracker", "Regulatory News Tracker", "SEC, CFTC, global crypto regulation news", "research"),
        ("macro_calendar", "Macro Economic Calendar", "FOMC, ECB, BOJ, NFP, CPI, GDP schedule", "research"),
        ("earnings_calendar_full", "Global Earnings Calendar", "Upcoming earnings for major companies", "research"),
    ];

    for (id, name, desc, subcat) in extra_skills {
        registry.register(ToolEntry {
            id: format!("xskill_{}", id),
            name: name.to_string(),
            category: Category::Skill,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Advanced,
            tags: vec!["skill".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Additional Indicators (20) ──────────────────────────────────
    let extra_indicators = vec![
        ("rsi_divergence", "RSI Divergence Detector", "Spot price-RSI divergence for reversal signals"),
        ("macd_histogram_div", "MACD Histogram Divergence", "Momentum divergence in histogram"),
        ("bollinger_squeeze", "Bollinger Squeeze", "Volatility contraction before breakout"),
        ("bollinger_bandwidth", "Bollinger Bandwidth", "Measure of volatility expansion/contraction"),
        ("bollinger_pct_b", "Bollinger %B", "Position within Bollinger bands"),
        ("atr_percentile", "ATR Percentile Rank", "Current ATR relative to historical ATR"),
        ("rsi_failure_swings", "RSI Failure Swings", "Overbought/oversold failure patterns"),
        ("stoch_rsi", "Stochastic RSI", "RSI of RSI for extreme readings"),
        ("williams_r_momentum", "Williams %R Momentum", "Rate of change of Williams %R"),
        ("cci_extremes", "CCI Extreme Zones", "CCI above +200 or below -200"),
        ("mfi_divergence", "Money Flow Divergence", "Volume-weighted RSI divergence"),
        ("adx_trend_strength", "ADX Trend Strength", "DI+ vs DI- crossover with ADX filter"),
        ("obv_divergence", "OBV Divergence", "Volume confirmation of price trend"),
        ("vwap_deviation", "VWAP Standard Deviation Bands", "Mean-reversion to VWAP"),
        ("pivot_floor_trader", "Floor Trader Pivots", "Modified pivot formula used by floor traders"),
        ("fib_time_zone", "Fibonacci Time Zones", "Time-based support/resistance"),
        ("gann_square", "Gann Square of 9", "Price-time geometric relationship"),
        ("huron_trend", "Hurst Exponent", "Trend persistence vs mean-reversion measure"),
        ("hurst_exponent", "Hurst Exponent Trend", "H > 0.5 = trending, H < 0.5 = mean-reverting"),
        ("fractal_adaptive", "Fractal Adaptive MA (FRAMA)", "MA that adapts to market efficiency"),
    ];

    for (id, name, desc) in extra_indicators {
        registry.register(ToolEntry {
            id: format!("indicator_ext_{}", id),
            name: name.to_string(),
            category: Category::Indicator,
            description: desc.to_string(),
            subcategory: "custom".to_string(),
            complexity: Complexity::Advanced,
            tags: vec!["indicator".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }

    // ── Additional ML Models (20) ───────────────────────────────────
    let extra_ml = vec![
        ("xgboost", "XGBoost", "Gradient boosted trees — most popular ML for tabular data"),
        ("lightgbm", "LightGBM", "Fast gradient boosting — large dataset friendly"),
        ("catboost", "CatBoost", "Gradient boosting with categorical feature support"),
        ("tabnet", "TabNet", "Attention-based tabular learning"),
        ("temporal_fusion", "Temporal Fusion Transformer", "Multi-horizon time series forecasting"),
        ("n_beats", "N-BEATS", "Neural basis expansion for time series"),
        ("prophet", "Prophet (Meta)", "Additive seasonality forecasting"),
        ("arima", "ARIMA", "Auto-regressive integrated moving average"),
        ("var_model", "Vector Autoregression", "Multi-variable time series model"),
        ("garch", "GARCH(1,1)", "Volatility clustering model"),
        ("egarch", "EGARCH", "Asymmetric volatility model — leverage effect"),
        ("tarch", "Threshold ARCH", "Regime-dependent volatility"),
        ("copula_model", "Copula Models", "Dependence structure beyond correlation"),
        ("extreme_value", "Extreme Value Theory", "Tail risk modeling"),
        ("regime_switching", "Markov Regime Switching", "State-dependent parameter models"),
        ("hidden_concat", "Hidden Concatenation Model", "Combine multiple data streams"),
        ("attention_mechanism", "Self-Attention Mechanism", "Learn temporal dependencies"),
        ("siamese_network", "Siamese Network", "Pattern similarity matching"),
        ("graph_neural", "Graph Neural Network", "Network relationship modeling"),
        ("variational_autoencoder", "VAE", "Generative anomaly detection"),
    ];

    for (id, name, desc) in extra_ml {
        registry.register(ToolEntry {
            id: format!("ml_ext_{}", id),
            name: name.to_string(),
            category: Category::MLModel,
            description: desc.to_string(),
            subcategory: "extended".to_string(),
            complexity: Complexity::Advanced,
            tags: vec!["ml".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });

    // ── Additional Web Tools (20) ───────────────────────────────────
    let extra_web = vec![
        ("proxycurl", "Proxycurl API", "LinkedIn profile scraping", "scraping"),
        ("serpapi", "SerpAPI", "Google search results API", "search"),
        ("tavily", "Tavily Search API", "AI-optimized web search", "search"),
        ("serper", "Serper API", "Google search — fast, cheap", "search"),
        ("newsapi_org", "NewsAPI.org", "70K+ news sources, 50+ languages", "news"),
        ("websearch_native", "Web Search (native)", "Built-in web search capability", "search"),
        ("rss_multi", "Multi-Feed RSS Aggregator", "Aggregate multiple RSS feeds simultaneously", "feed"),
        ("websocket_client", "WebSocket Client", "Persistent bidirectional data streams", "stream"),
        ("grpc_client", "gRPC Client", "High-performance RPC communication", "rpc"),
        ("graphql_client", "GraphQL Client", "Flexible API query language", "api"),
        ("sse_client", "Server-Sent Events Client", "Server push notification stream", "stream"),
        ("ipfs_gateway", "IPFS Gateway", "Decentralized content retrieval", "web3"),
        ("the_graph", "The Graph Protocol", "Decentralized blockchain indexing", "web3"),
        ("ens_resolve", "ENS Resolution", "Ethereum Name Service resolution", "web3"),
        ("wallet_connect", "WalletConnect", "Connect to crypto wallets", "web3"),
        ("pdf_parser", "PDF Parser", "Extract data from financial PDFs", "extraction"),
        ("csv_parser", "CSV Parser", "Structured data ingestion", "extraction"),
        ("excel_parser", "Excel Parser", "Parse Excel spreadsheets", "extraction"),
        ("xml_parser", "XML Parser", "Parse XML financial data (XBRL)", "extraction"),
        ("protobuf_client", "Protocol Buffers Client", "Binary protocol for market data", "serialization"),
    ];
    for (id, name, desc, subcat) in extra_web {
        registry.register(ToolEntry {
            id: format!("web_ext_{}", id),
            name: name.to_string(),
            category: Category::WebTool,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["web".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }
    // ── Final batch: 182 more entries ───────────────────────────────
    let final_batch = vec![
        // Additional Thinking Styles (10)
        (Category::ThinkingStyle, "ts_risk_parity_think", "Risk Parity Thinking", "Allocate by equal risk contribution", "allocation"),
        (Category::ThinkingStyle, "ts_carry_think", "Carry Thinking", "Earn yield differential as primary return source", "yield"),
        (Category::ThinkingStyle, "ts_volatility_think", "Volatility Selling", "Sell premium when implied > realized vol", "volatility"),
        (Category::ThinkingStyle, "ts_gamma_think", "Gamma Scalping", "Delta-hedge options for gamma profit", "options"),
        (Category::ThinkingStyle, "ts_spread_think", "Spread Trading", "Trade relative value between correlated instruments", "spread"),
        (Category::ThinkingStyle, "ts_calendar_think", "Calendar Spread Thinking", "Exploit term structure distortions", "term-structure"),
        (Category::ThinkingStyle, "ts_conversion_think", "Conversion/Reversal", "Arbitrage between convertible bond and stock", "arbitrage"),
        (Category::ThinkingStyle, "ts_merger_think", "Merger Arbitrage", "Trade M&A spreads — deal close probability", "event"),
        (Category::ThinkingStyle, "ts_distressed_think", "Distressed Investing", "Buy below recovery value in bankruptcy", "credit"),
        (Category::ThinkingStyle, "ts_vol_arb_think", "Volatility Arbitrage", "Trade difference between implied and realized vol", "volatility"),
        // Additional Decision Models (10)
        (Category::DecisionModel, "dm_sharpe_optimal", "Optimal f-star from Sharpe", "Kelly fraction derived from Sharpe ratio", "sizing"),
        (Category::DecisionModel, "dm_vol_target", "Volatility Targeting", "Scale position to maintain constant portfolio vol", "sizing"),
        (Category::DecisionModel, "dm_risk_budget", "Risk Budgeting", "Allocate risk budget across strategies", "allocation"),
        (Category::DecisionModel, "dm_drawdown_limit", "Drawdown Limit Sizing", "Reduce size as drawdown approaches limit", "sizing"),
        (Category::DecisionModel, "dm_information_ratio", "Information Ratio Sizing", "Scale by tracking error budget", "sizing"),
        (Category::DecisionModel, "dm_correlation_adjusted", "Correlation-Adjusted Sizing", "Account for correlation in portfolio risk", "sizing"),
        (Category::DecisionModel, "dm_regime_sizing", "Regime-Adaptive Sizing", "Adjust size based on detected market regime", "sizing"),
        (Category::DecisionModel, "dm_conviction_sizing", "Conviction-Based Sizing", "Scale by model confidence level", "sizing"),
        (Category::DecisionModel, "dm_time_decay", "Time Decay Model", "Position value erosion from theta", "options"),
        (Category::DecisionModel, "dm_margin_of_safety", "Margin of Safety", "Buy only below intrinsic value with buffer", "value"),
        // Additional Risk Metrics (10)
        (Category::RiskMetric, "rm_conditional_drawdown", "Conditional Drawdown at Risk", "Expected drawdown beyond threshold", "drawdown"),
        (Category::RiskMetric, "rm_moment", "Moment-Based Risk", "Higher moments for non-normal distributions", "tail"),
        (Category::RiskMetric, "rm_semi_deviation", "Semi-Deviation", "Downside deviation only", "downside"),
        (Category::RiskMetric, "rm_downside_deviation", "Downside Deviation", "StdDev of negative returns only", "downside"),
        (Category::RiskMetric, "rm_information_coefficient", "Information Coefficient", "Correlation of predictions vs actual", "alpha"),
        (Category::RiskMetric, "rm_tracking_error", "Tracking Error", "StdDev of active returns", "active"),
        (Category::RiskMetric, "rm_active_share", "Active Share", "How different from benchmark", "active"),
        (Category::RiskMetric, "rm_capacity", "Strategy Capacity", "Max capital before alpha decays", "capacity"),
        (Category::RiskMetric, "rm_decay_rate", "Alpha Decay Rate", "How fast edge disappears with AUM", "capacity"),
        (Category::RiskMetric, "rm_fill_rate", "Order Fill Rate", "% of orders successfully filled", "execution"),
        // Additional Execution Algos (10)
        (Category::ExecutionAlgo, "ea_joine", "Joine (Adaptive)", "Join best bid/ask adaptively", "passive"),
        (Category::ExecutionAlgo, "ea_guerrilla", "Guerrilla", "Aggressive hidden liquidity hunting", "aggressive"),
        (Category::ExecutionAlgo, "ea_stealth", "Stealth Order", "Minimize information leakage", "hidden"),
        (Category::ExecutionAlgo, "ea_bait", "Bait and Switch", "Display small, execute large", "hidden"),
        (Category::ExecutionAlgo, "ea_icebergsweep", "Iceberg Sweep", "Detect and sweep hidden liquidity", "aggressive"),
        (Category::ExecutionAlgo, "ea_round_trip", "Round-Trip Test", "Small buy+sell to measure market impact", "testing"),
        (Category::ExecutionAlgo, "ea_multi_venue", "Multi-Venue Sweep", "Route across multiple exchanges", "smart"),
        (Category::ExecutionAlgo, "ea_dark_pool_route", "Dark Pool Routing", "Route to minimize information leakage", "hidden"),
        (Category::ExecutionAlgo, "ea_block_trade", "Block Trade / RFQ", "Negotiate large trades off-book", "institutional"),
        (Category::ExecutionAlgo, "ea_atr_entry", "ATR-Based Entry", "Enter at optimal distance from current price", "entry"),
        // Additional On-Chain (10)
        (Category::OnChainTool, "oc_defi_yield_farming", "DeFi Yield Farming Monitor", "Track yield farming opportunities across protocols", "defi"),
        (Category::OnChainTool, "oc_liquidation_map", "Liquidation Heatmap", "Visualize concentration of leveraged positions", "derivatives"),
        (Category::OnChainTool, "oc_whale_cluster", "Whale Cluster Detection", "Identify accumulation zones from whale activity", "flow"),
        (Category::OnChainTool, "oc_exchange_flows_hourly", "Hourly Exchange Flows", "Granular exchange inflow/outflow tracking", "flow"),
        (Category::OnChainTool, "oc_miner_capitulation", "Miner Capitulation Index", "Hash rate drop + selling = capitulation", "mining"),
        (Category::OnChainTool, "oc_realized_price", "Realized Price Line", "Aggregate cost basis — support/resistance", "valuation"),
        (Category::OnChainTool, "oc_accumulation_distrib", "On-Chain Accumulation/Distribution", "Smart money vs retail positioning", "behavior"),
        (Category::OnChainTool, "oc_entity_clusters", "Entity Cluster Analysis", "Group blockchain addresses into entities", "analysis"),
        (Category::OnChainTool, "oc_cross_chain_flows", "Cross-Chain Bridge Flows", "Track assets moving between blockchains", "flow"),
        (Category::OnChainTool, "oc_l1_activity", "L1 Blockchain Activity", "Transaction count, fees, active users", "network"),
        // Additional Sentiment (10)
        (Category::SentimentTool, "st_mempool_fear", "Mempool Fear Gauge", "Transaction backlog indicates network stress", "network"),
        (Category::SentimentTool, "st_gas_greed", "Gas Price Greed", "Willingness to pay for block space", "network"),
        (Category::SentimentTool, "st_whale_alert_sentiment", "Whale Alert Sentiment", "Large transaction directional bias", "flow"),
        (Category::SentimentTool, "st_tvl_change", "TVL Change Rate", "DeFi capital flow direction", "defi"),
        (Category::SentimentTool, "st_nft_sentiment", "NFT Market Sentiment", "Floor price trends as risk appetite gauge", "nft"),
        (Category::SentimentTool, "st_stablecoin_mcap", "Stablecoin Market Cap Change", "New stablecoins = buying power", "flow"),
        (Category::SentimentTool, "st_open_interest_change_rate", "OI Change Rate", "Speed of new leverage entering market", "derivatives"),
        (Category::SentimentTool, "st_basis_spread", "Futures Basis Spread", "Contango/backwardation = sentiment", "derivatives"),
        (Category::SentimentTool, "st_miner_positioning", "Miner Positioning", "Miner selling vs holding behavior", "mining"),
        (Category::SentimentTool, "st_institutional_flows", "Institutional Flow Gauge", "ETF flows, CME positioning", "institutional"),
        // Additional Data Sources (20)
        (Category::DataSource, "ds_binance_perp_metrics", "Binance Perpetual Metrics", "Funding, OI, long/short across all pairs", "derivatives"),
        (Category::DataSource, "ds_okx_funding", "OKX Funding Rates", "OKX perpetual funding rates", "derivatives"),
        (Category::DataSource, "ds_bybit_funding", "Bybit Funding Rates", "Bybit perpetual funding rates", "derivatives"),
        (Category::DataSource, "ds_deribit_options", "Deribit Options Chain", "BTC/ETH options data — strikes, IV, Greeks", "options"),
        (Category::DataSource, "ds_deribit_volatility", "Deribit Volatility Index", "DVOL — crypto VIX equivalent", "volatility"),
        (Category::DataSource, "ds_bitmex_funding", "BitMEX Funding Rate", "Historical funding rate data", "derivatives"),
        (Category::DataSource, "ds_coingecko_trending", "CoinGecko Trending", "Currently trending tokens", "social"),
        (Category::DataSource, "ds_coingecko_top_gainers", "CoinGecko Top Gainers", "Biggest movers in last 24h", "market"),
        (Category::DataSource, "ds_token_terminal", "Token Terminal", "Crypto protocol revenue data", "fundamentals"),
        (Category::DataSource, "ds_l2_fees", "L2 Fees", "Layer 2 transaction costs", "network"),
        (Category::DataSource, "ds_eth_gas_now", "ETH Gas Tracker", "Current gas prices and estimates", "network"),
        (Category::DataSource, "ds_mempool_space", "Mempool.space API", "BTC mempool and fee estimation", "btc"),
        (Category::DataSource, "ds_chainlink_feeds", "Chainlink Price Feeds", "Decentralized oracle price data", "defi"),
        (Category::DataSource, "ds_uniswap_v3", "Uniswap V3 API", "DEX liquidity and pricing data", "defi"),
        (Category::DataSource, "ds_aave_rates", "Aave Lending Rates", "DeFi lending/borrowing rates", "defi"),
        (Category::DataSource, "ds_compound_rates", "Compound Rates", "DeFi lending protocol rates", "defi"),
        (Category::DataSource, "ds_maker_stability", "Maker Stability Fee", "DAI stability fee — DeFi benchmark rate", "defi"),
        (Category::DataSource, "ds_opensea_floor", "OpenSea Floor Prices", "NFT market data — blue chip collections", "nft"),
        (Category::DataSource, "ds_dune_custom", "Dune Custom Query", "Execute custom SQL against blockchain", "custom"),
        (Category::DataSource, "ds_flipside", "Flipside Crypto", "Free blockchain analytics platform", "analytics"),
        // Additional News (15)
        (Category::NewsSource, "ns_bitcoin_magazine", "Bitcoin Magazine", "Bitcoin-focused news and analysis", "btc"),
        (Category::NewsSource, "ns_defi_pulse", "DeFi Pulse", "DeFi ecosystem news and TVL tracking", "defi"),
        (Category::NewsSource, "ns_the_defiant", "The Defiant", "DeFi-focused journalism", "defi"),
        (Category::NewsSource, "ns_bankless", "Bankless", "Crypto/Web3 media and podcast", "web3"),
        (Category::NewsSource, "ns_crypto_briefing", "Crypto Briefing", "Altcoin and DeFi analysis", "altcoin"),
        (Category::NewsSource, "ns_btc_times", "BTC Times", "Bitcoin macro and policy news", "btc"),
        (Category::NewsSource, "ns_unchained", "Unchained", "Crypto institutional news", "institutional"),
        (Category::NewsSource, "ns_delphi_digital", "Delphi Digital", "Institutional crypto research", "research"),
        (Category::NewsSource, "ns_finance_yahoo", "Yahoo Finance RSS", "General finance and markets", "finance"),
        (Category::NewsSource, "ns_marketwatch", "MarketWatch", "US market news and analysis", "finance"),
        (Category::NewsSource, "ns_ft_markets", "Financial Times Markets", "Global financial news", "finance"),
        (Category::NewsSource, "ns_wsj_markets", "WSJ Markets", "Wall Street Journal markets section", "finance"),
        (Category::NewsSource, "ns_barrons", "Barron's", "Investment analysis and market commentary", "finance"),
        (Category::NewsSource, "ns_investors_business_daily", "Investor's Business Daily", "CAN SLIM and growth stock analysis", "equity"),
        (Category::NewsSource, "ns_motley_fool", "The Motley Fool", "Stock analysis and investment advice", "equity"),
        // Additional Web Tools (12)
        (Category::WebTool, "wt_cdp_browser", "CDP Browser Automation", "Chrome DevTools Protocol direct control", "browser"),
        (Category::WebTool, "wt_headless_firefox", "Headless Firefox", "Mozilla-based headless browsing", "browser"),
        (Category::WebTool, "wt_webdriver", "WebDriver (W3C Standard)", "Cross-browser automation standard", "browser"),
        (Category::WebTool, "wt_selenium_rust", "Selenium Rust Client", "Selenium WebDriver bindings", "browser"),
        (Category::WebTool, "wt_captcha_solver", "CAPTCHA Solver Service", "Automated CAPTCHA resolution", "bypass"),
        (Category::WebTool, "wt_proxy_rotator", "Proxy Rotator", "Rotate IP addresses for scraping", "proxy"),
        (Category::WebTool, "wt_rate_limiter", "Rate Limiter", "Respect API rate limits automatically", "utility"),
        (Category::WebTool, "wt_retry_logic", "Exponential Backoff Retry", "Automatic retry with backoff", "utility"),
        (Category::WebTool, "wt_cache_layer", "HTTP Cache Layer", "Cache responses to reduce API calls", "utility"),
        (Category::WebTool, "wt_request_signer", "API Request Signer", "HMAC-SHA256 signature generation", "auth"),
        (Category::WebTool, "wt_webhook_receiver", "Webhook Receiver", "Accept incoming webhook data", "incoming"),
        (Category::WebTool, "wt_grpc_server", "gRPC Server", "High-performance RPC server for data", "server"),
        // Additional Patterns (6)
        (Category::PatternType, "pt_wolfe_wave", "Wolfe Wave", "5-point reversal pattern using price symmetry", "harmonic"),
        (Category::PatternType, "pt_gartley", "Gartley Pattern", "Fibonacci-based harmonic pattern — 222", "harmonic"),
        (Category::PatternType, "pt_butterfly", "Butterfly Pattern", "Fibonacci extension harmonic", "harmonic"),
        (Category::PatternType, "pt_bat", "Bat Pattern", "Fibonacci 0.886 retracement harmonic", "harmonic"),
        (Category::PatternType, "pt_crab", "Crab Pattern", "Extended harmonic — 1.618 extension", "harmonic"),
        (Category::PatternType, "pt_abcd", "ABCD Pattern", "Basic three-drive harmonic pattern", "harmonic"),
        // Additional Regimes (5)
        (Category::RegimeType, "rt_deflation", "Deflationary Regime", "Falling prices — bonds outperform", "macro"),
        (Category::RegimeType, "rt_inflation", "Inflationary Regime", "Rising prices — commodities outperform", "macro"),
        (Category::RegimeType, "rt_stagflation", "Stagflation Regime", "Rising prices + slowing growth", "macro"),
        (Category::RegimeType, "rt_reflation", "Reflation Regime", "Recovery from deflation — risk-on", "macro"),
        (Category::RegimeType, "rt_monetary_tightening", "Monetary Tightening", "Rising rates — risk-off for duration assets", "macro"),
        // Additional Portfolio Methods (5)
        (Category::PortfolioMethod, "pm_dynamic_hedging", "Dynamic Hedging", "Continuously adjust hedges as market moves", "hedging"),
        (Category::PortfolioMethod, "pm_options_overlay", "Options Overlay", "Add options positions for tail protection", "options"),
        (Category::PortfolioMethod, "pm_barbell_strategy", "Barbell Strategy", "Combine extreme safety with small high-risk bets", "allocation"),
        (Category::PortfolioMethod, "pm_core_satellite", "Core-Satellite", "Large passive core + small active satellites", "allocation"),
        (Category::PortfolioMethod, "pm_trend_overlay", "Trend Overlay", "Adjust allocation based on trend signals", "timing"),
    ];
    for (cat, id, name, desc, subcat) in final_batch {
        registry.register(ToolEntry {
            id: id.to_string(),
            name: name.to_string(),
            category: cat,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["ecosystem".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }
}
    // ── Final 59 to hit 1000 ────────────────────────────────────────
    let stretch = vec![
        // More News (10)
        (Category::NewsSource, "ns_crypto_briefing_alt", "Crypto Briefing Altcoins", "Altcoin news and analysis", "altcoin"),
        (Category::NewsSource, "ns_coindesk_bites", "CoinDesk Quick Bites", "Breaking crypto news snippets", "breaking"),
        (Category::NewsSource, "ns_the_block_data", "The Block Data", "On-chain and market data analytics", "data"),
        (Category::NewsSource, "ns_dl_news", "DL News", "Crypto and DeFi breaking news", "defi"),
        (Category::NewsSource, "ns_watch_guru", "CoinDCX Guru", "Indian crypto market analysis", "india"),
        (Category::NewsSource, "ns_bitwise", "Bitwise Insights", "Institutional crypto research", "institutional"),
        (Category::NewsSource, "ns_grayscale", "Grayscale Research", "Digital asset market analysis", "research"),
        (Category::NewsSource, "ns_pantera", "Pantera Capital", "Blockchain venture research", "venture"),
        (Category::NewsSource, "ns_multicoin", "Multicoin Capital", "Crypto thesis-driven research", "research"),
        (Category::NewsSource, "nsPlaceholder", "Placeholder Ventures", "Crypto capital allocation research", "research"),
        // More Sentiment (10)
        (Category::SentimentTool, "st_nansen_smart_money", "Nansen Smart Money Flow", "Track smart money wallet movements", "onchain"),
        (Category::SentimentTool, "st_dune_whale", "Dune Whale Tracker", "SQL-based whale monitoring", "onchain"),
        (Category::SentimentTool, "st_coinglass_funding", "Coinglass Funding", "Aggregate funding rates across exchanges", "derivatives"),
        (Category::SentimentTool, "st_coinglass_oi", "Coinglass Open Interest", "Aggregate OI across exchanges", "derivatives"),
        (Category::SentimentTool, "st_coinglass_longshort", "Coinglass Long/Short", "Aggregate long/short ratios", "derivatives"),
        (Category::SentimentTool, "st_aggregate_sentiment", "Aggregate Market Sentiment", "Combined social + on-chain + derivatives score", "composite"),
        (Category::SentimentTool, "st_retail_vs_smart", "Retail vs Smart Money", "Compare retail and institutional positioning", "contrast"),
        (Category::SentimentTool, "st_options_skew_sentiment", "Options Skew Sentiment", "Put/call IV skew as fear gauge", "options"),
        (Category::SentimentTool, "st_stablecoin_dominance", "Stablecoin Dominance", "Stablecoin % of total crypto market cap", "market"),
        (Category::SentimentTool, "st_btc_dominance", "Bitcoin Dominance", "BTC % of total crypto market cap", "market"),
        // More Indicators (10)
        (Category::Indicator, "ind_vwap_std_bands", "VWAP Standard Deviation Bands", "Bands around VWAP for mean reversion", "vwap"),
        (Category::Indicator, "ind_cvd", "Cumulative Volume Delta", "Net buying vs selling pressure", "volume"),
        (Category::Indicator, "ind_absorption", "Absorption Detector", "Detect large orders absorbing liquidity", "orderflow"),
        (Category::Indicator, "ind_delta_divergence", "Delta Divergence", "Price vs volume delta divergence", "orderflow"),
        (Category::Indicator, "ind_footprint", "Footprint Chart", "Volume at each price level within candle", "orderflow"),
        (Category::Indicator, "ind_heatmap", "Order Book Heatmap", "Visualize order book depth over time", "orderflow"),
        (Category::Indicator, "ind_speed_of_light", "Speed of Light", "Rate of price change indicator", "momentum"),
        (Category::Indicator, "ind_roc_extended", "Rate of Change Extended", "Multi-period ROC with smoothing", "momentum"),
        (Category::Indicator, "ind_momentum_osc", "Momentum Oscillator", "Distance from N-period moving average", "momentum"),
        (Category::Indicator, "ind_price_channel", "Donchian Price Channel", "Highest high / lowest low over N periods", "channel"),
        // More Risk Models (5)
        (Category::RiskModel, "rm_tail_conditional", "Tail Conditional Expectation", "Expected loss given tail event", "tail"),
        (Category::RiskModel, "rm_max_drawdown_duration", "Max Drawdown Duration", "Longest time from peak to recovery", "drawdown"),
        (Category::RiskModel, "rm_hurst_exponent_risk", "Hurst Exponent Risk", "Mean-reversion vs trending risk profile", "regime"),
        (Category::RiskModel, "rm_regime_var", "Regime-Switching VaR", "VaR that adapts to detected regime", "regime"),
        (Category::RiskModel, "rm_component_var", "Component VaR", "VaR contribution of each position", "attribution"),
        // More ML Models (10)
        (Category::MLModel, "ml_isolation_forest", "Isolation Forest", "Unsupervised anomaly detection", "anomaly"),
        (Category::MLModel, "ml_one_class_svm", "One-Class SVM", "Novelty detection for market regimes", "anomaly"),
        (Category::MLModel, "ml_mahalanobis", "Mahalanobis Distance", "Multivariate outlier detection", "anomaly"),
        (Category::MLModel, "ml_dynamic_time_wrap", "Dynamic Time Warping", "Time series pattern matching", "similarity"),
        (Category::MLModel, "ml_prophet_decomp", "Prophet Decomposition", "Trend + seasonality + residual", "forecasting"),
        (Category::MLModel, "ml_ets", "Exponential Smoothing", "Holt-Winters time series forecasting", "forecasting"),
        (Category::MLModel, "ml_lstm_attention", "LSTM with Attention", "Sequence model with attention mechanism", "deep"),
        (Category::MLModel, "ml_tcn", "Temporal Convolutional Net", "Causal convolutions for time series", "deep"),
        (Category::MLModel, "ml_wavenet", "WaveNet Architecture", "Dilated causal convolution model", "deep"),
        (Category::MLModel, "ml_boltzmann", "Restricted Boltzmann Machine", "Unsupervised feature learning", "unsupervised"),
        // More Web Tools (8)
        (Category::WebTool, "wt_cors_proxy", "CORS Proxy", "Bypass CORS for cross-origin requests", "proxy"),
        (Category::WebTool, "wt_tls_fingerprint", "TLS Fingerprint Rotation", "Rotate browser TLS fingerprints", "stealth"),
        (Category::WebTool, "wt_cookie_jar", "Cookie Jar Manager", "Manage session cookies for auth", "auth"),
        (Category::WebTool, "wt_html_cleaner", "HTML Content Cleaner", "Strip ads/nav for clean content", "extraction"),
        (Category::WebTool, "wt_link_crawler", "Recursive Link Crawler", "Crawl website links breadth-first", "crawler"),
        (Category::WebTool, "wt_screenshot", "Page Screenshot", "Capture webpage as image", "capture"),
        (Category::WebTool, "wt_pdf_generator", "PDF Report Generator", "Generate PDF reports from data", "report"),
        (Category::WebTool, "wt_chart_renderer", "Chart Renderer Server", "Server-side chart image generation", "visual"),
        // More On-Chain (6)
        (Category::OnChainTool, "oc_btc_dominance_onchain", "BTC Dominance On-Chain", "BTC share of on-chain activity", "network"),
        (Category::OnChainTool, "oc_eth_burn_rate", "ETH Burn Rate", "EIP-1559 fee burning — supply reduction", "eth"),
        (Category::OnChainTool, "oc_l2_total_tvl", "L2 Total TVL", "Aggregate Layer 2 locked value", "l2"),
        (Category::OnChainTool, "oc_bridge_volume", "Bridge Volume Tracker", "Cross-chain bridge transfer volumes", "bridge"),
        (Category::OnChainTool, "oc_nft_volume", "NFT Trading Volume", "Daily NFT marketplace volume", "nft"),
        (Category::OnChainTool, "oc_dao_treasury", "DAO Treasury Sizes", "Track governance token treasury values", "dao"),
    ];
    for (cat, id, name, desc, subcat) in stretch {
        registry.register(ToolEntry {
            id: id.to_string(),
            name: name.to_string(),
            category: cat,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity: Complexity::Intermediate,
            tags: vec!["final".into(), id.into()],
            implementation: Implementation::BuiltIn,
        });
    }
}