use crate::registry::{Category, Complexity, Implementation, ToolEntry};

/// All technical indicators available in the ecosystem
pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let indicators = vec![
        // ── Trend ──────────────────────────────────────────────────────
        (
            "sma_10",
            "SMA (10)",
            "10-period Simple Moving Average — short-term trend",
            "trend",
            vec!["indicator", "trend", "sma", "moving_average", "simple"],
            Complexity::Basic,
        ),
        (
            "sma_20",
            "SMA (20)",
            "20-period Simple Moving Average — intermediate-term trend",
            "trend",
            vec!["indicator", "trend", "sma", "moving_average", "simple"],
            Complexity::Basic,
        ),
        (
            "sma_50",
            "SMA (50)",
            "50-period Simple Moving Average — medium-term trend",
            "trend",
            vec!["indicator", "trend", "sma", "moving_average", "simple"],
            Complexity::Basic,
        ),
        (
            "sma_100",
            "SMA (100)",
            "100-period Simple Moving Average — long-term trend",
            "trend",
            vec!["indicator", "trend", "sma", "moving_average", "simple"],
            Complexity::Basic,
        ),
        (
            "sma_200",
            "SMA (200)",
            "200-period Simple Moving Average — major trend filter",
            "trend",
            vec!["indicator", "trend", "sma", "moving_average", "simple"],
            Complexity::Basic,
        ),
        (
            "ema_9",
            "EMA (9)",
            "9-period Exponential Moving Average — fast trend",
            "trend",
            vec!["indicator", "trend", "ema", "moving_average", "exponential"],
            Complexity::Basic,
        ),
        (
            "ema_12",
            "EMA (12)",
            "12-period Exponential Moving Average — short-term trend",
            "trend",
            vec!["indicator", "trend", "ema", "moving_average", "exponential"],
            Complexity::Basic,
        ),
        (
            "ema_21",
            "EMA (21)",
            "21-period Exponential Moving Average — swing trading trend",
            "trend",
            vec!["indicator", "trend", "ema", "moving_average", "exponential"],
            Complexity::Basic,
        ),
        (
            "ema_26",
            "EMA (26)",
            "26-period Exponential Moving Average — MACD component trend",
            "trend",
            vec!["indicator", "trend", "ema", "moving_average", "exponential"],
            Complexity::Basic,
        ),
        (
            "ema_50",
            "EMA (50)",
            "50-period Exponential Moving Average — intermediate trend",
            "trend",
            vec!["indicator", "trend", "ema", "moving_average", "exponential"],
            Complexity::Basic,
        ),
        (
            "ema_100",
            "EMA (100)",
            "100-period Exponential Moving Average — long-term trend",
            "trend",
            vec!["indicator", "trend", "ema", "moving_average", "exponential"],
            Complexity::Basic,
        ),
        (
            "ema_200",
            "EMA (200)",
            "200-period Exponential Moving Average — major trend filter",
            "trend",
            vec!["indicator", "trend", "ema", "moving_average", "exponential"],
            Complexity::Basic,
        ),
        (
            "wma",
            "Weighted Moving Average",
            "Linear-weighted moving average — recent data weighted more",
            "trend",
            vec!["indicator", "trend", "wma", "moving_average", "weighted"],
            Complexity::Intermediate,
        ),
        (
            "dema",
            "Double EMA (DEMA)",
            "Double Exponential Moving Average — reduced lag trend",
            "trend",
            vec![
                "indicator",
                "trend",
                "dema",
                "moving_average",
                "exponential",
            ],
            Complexity::Intermediate,
        ),
        (
            "tema",
            "Triple EMA (TEMA)",
            "Triple Exponential Moving Average — minimal lag trend",
            "trend",
            vec![
                "indicator",
                "trend",
                "tema",
                "moving_average",
                "exponential",
            ],
            Complexity::Intermediate,
        ),
        (
            "kama",
            "Kaufman Adaptive MA (KAMA)",
            "Adaptive moving average that adjusts to market noise",
            "trend",
            vec!["indicator", "trend", "kama", "adaptive", "moving_average"],
            Complexity::Advanced,
        ),
        (
            "hull_ma",
            "Hull Moving Average",
            "Near-zero lag moving average using weighted midpoints",
            "trend",
            vec!["indicator", "trend", "hull", "moving_average", "low-lag"],
            Complexity::Intermediate,
        ),
        (
            "vidya",
            "VIDYA",
            "Variable Index Dynamic Average — volatility-adjusted trend",
            "trend",
            vec!["indicator", "trend", "vidya", "adaptive", "volatility"],
            Complexity::Advanced,
        ),
        (
            "mcginley",
            "McGinley Dynamic",
            "Smoothing indicator that adjusts to speed of price changes",
            "trend",
            vec!["indicator", "trend", "mcginley", "adaptive", "smoothing"],
            Complexity::Intermediate,
        ),
        (
            "alma",
            "Arnaud-Legoux MA (ALMA)",
            "Gaussian-weighted moving average with configurable offset",
            "trend",
            vec!["indicator", "trend", "alma", "gaussian", "moving_average"],
            Complexity::Advanced,
        ),
        (
            "fractal_adaptive_ma",
            "Fractal Adaptive MA (FRAMA)",
            "Fractal dimension adaptive moving average",
            "trend",
            vec!["indicator", "trend", "frama", "fractal", "adaptive"],
            Complexity::Advanced,
        ),
        (
            "zigzag",
            "ZigZag",
            "Filters noise to identify significant swing points",
            "trend",
            vec!["indicator", "trend", "zigzag", "swing", "filter"],
            Complexity::Intermediate,
        ),
        // ── Momentum ───────────────────────────────────────────────────
        (
            "rsi",
            "Relative Strength Index (RSI)",
            "Measures speed and magnitude of price changes — overbought/oversold",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "rsi",
                "oscillator",
                "overbought",
                "oversold",
            ],
            Complexity::Basic,
        ),
        (
            "macd",
            "MACD",
            "Moving Average Convergence Divergence — trend and momentum",
            "momentum",
            vec!["indicator", "momentum", "macd", "trend", "divergence"],
            Complexity::Basic,
        ),
        (
            "stochastic_kd",
            "Stochastic (K/D)",
            "Stochastic Oscillator %K and %D — momentum oscillator",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "stochastic",
                "oscillator",
                "overbought",
                "oversold",
            ],
            Complexity::Basic,
        ),
        (
            "cci",
            "Commodity Channel Index (CCI)",
            "Measures price deviation from statistical mean",
            "momentum",
            vec!["indicator", "momentum", "cci", "oscillator", "cyclical"],
            Complexity::Intermediate,
        ),
        (
            "williams_r",
            "Williams %R",
            "Momentum oscillator measuring overbought/oversold levels",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "williams",
                "oscillator",
                "overbought",
                "oversold",
            ],
            Complexity::Basic,
        ),
        (
            "mfi",
            "Money Flow Index (MFI)",
            "Volume-weighted RSI — price and volume momentum",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "mfi",
                "oscillator",
                "volume",
                "overbought",
            ],
            Complexity::Intermediate,
        ),
        (
            "roc",
            "Rate of Change (ROC)",
            "Percentage change between current and N-period-ago price",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "roc",
                "rate_of_change",
                "percentage",
            ],
            Complexity::Basic,
        ),
        (
            "momentum",
            "Momentum",
            "Raw difference between current price and N-period-ago price",
            "momentum",
            vec!["indicator", "momentum", "raw", "price_difference"],
            Complexity::Basic,
        ),
        (
            "tsi",
            "True Strength Index (TSI)",
            "Double-smoothed momentum oscillator",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "tsi",
                "oscillator",
                "double_smoothed",
            ],
            Complexity::Intermediate,
        ),
        (
            "ultimate_oscillator",
            "Ultimate Oscillator",
            "Weighted average of three momentum timeframes",
            "momentum",
            vec!["indicator", "momentum", "oscillator", "multi-timeframe"],
            Complexity::Intermediate,
        ),
        (
            "awesome_oscillator",
            "Awesome Oscillator (AO)",
            "5-period vs 34-period SMA midpoint difference — trend momentum",
            "momentum",
            vec!["indicator", "momentum", "ao", "oscillator", "bill_williams"],
            Complexity::Basic,
        ),
        (
            "aroon",
            "Aroon",
            "Measures time since highest/lowest price — trend strength and direction",
            "momentum",
            vec!["indicator", "momentum", "aroon", "trend", "strength"],
            Complexity::Intermediate,
        ),
        (
            "choppiness_index",
            "Choppiness Index",
            "Measures market directionality vs ranging",
            "momentum",
            vec!["indicator", "momentum", "chop", "range", "directional"],
            Complexity::Intermediate,
        ),
        (
            "kst",
            "Know Sure Thing (KST)",
            "Rate of change oscillator with multiple timeframes",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "kst",
                "oscillator",
                "multi-timeframe",
            ],
            Complexity::Advanced,
        ),
        (
            "trix",
            "TRIX",
            "Triple exponential smoothed rate of change — momentum oscillator",
            "momentum",
            vec![
                "indicator",
                "momentum",
                "trix",
                "oscillator",
                "triple_smoothed",
            ],
            Complexity::Advanced,
        ),
        (
            "dpo",
            "Detrended Price Oscillator (DPO)",
            "Removes trend component to isolate cycles",
            "momentum",
            vec!["indicator", "momentum", "dpo", "cycle", "detrended"],
            Complexity::Intermediate,
        ),
        (
            "ppo",
            "Percentage Price Oscillator (PPO)",
            "Percentage difference between two EMAs — relative momentum",
            "momentum",
            vec!["indicator", "momentum", "ppo", "percentage", "ema"],
            Complexity::Intermediate,
        ),
        // ── Volatility ─────────────────────────────────────────────────
        (
            "atr",
            "Average True Range (ATR)",
            "Average of true range bars — measures volatility",
            "volatility",
            vec!["indicator", "volatility", "atr", "range", "true_range"],
            Complexity::Basic,
        ),
        (
            "bollinger_bands",
            "Bollinger Bands",
            "SMA ± k standard deviations — volatility envelope",
            "volatility",
            vec![
                "indicator",
                "volatility",
                "bollinger",
                "bands",
                "standard_deviation",
            ],
            Complexity::Basic,
        ),
        (
            "keltner_channel",
            "Keltner Channel",
            "EMA ± ATR multiplier — volatility channel",
            "volatility",
            vec!["indicator", "volatility", "keltner", "channel", "atr"],
            Complexity::Intermediate,
        ),
        (
            "donchian_channel",
            "Donchian Channel",
            "Highest high / lowest low over N periods — breakout channel",
            "volatility",
            vec!["indicator", "volatility", "donchian", "channel", "breakout"],
            Complexity::Basic,
        ),
        (
            "std_dev",
            "Standard Deviation",
            "Statistical measure of price dispersion — volatility",
            "volatility",
            vec![
                "indicator",
                "volatility",
                "std",
                "standard_deviation",
                "dispersion",
            ],
            Complexity::Basic,
        ),
        (
            "historical_volatility",
            "Historical Volatility",
            "Annualized standard deviation of log returns",
            "volatility",
            vec!["indicator", "volatility", "hvol", "annualized", "returns"],
            Complexity::Intermediate,
        ),
        (
            "garman_klass",
            "Garman-Klass Volatility",
            "OHLC-based volatility estimator — more efficient than close-to-close",
            "volatility",
            vec![
                "indicator",
                "volatility",
                "garman_klass",
                "ohlc",
                "estimator",
            ],
            Complexity::Advanced,
        ),
        (
            "parkinson",
            "Parkinson Volatility",
            "High-low based volatility estimator",
            "volatility",
            vec![
                "indicator",
                "volatility",
                "parkinson",
                "high_low",
                "estimator",
            ],
            Complexity::Advanced,
        ),
        (
            "yang_zhang",
            "Yang-Zhang Volatility",
            "Unbiased OHLC volatility estimator combining overnight and intraday",
            "volatility",
            vec!["indicator", "volatility", "yang_zhang", "ohlc", "unbiased"],
            Complexity::Expert,
        ),
        (
            "chandelier_exit",
            "Chandelier Exit",
            "ATR-based trailing stop for trend following",
            "volatility",
            vec![
                "indicator",
                "volatility",
                "chandelier",
                "trailing_stop",
                "atr",
            ],
            Complexity::Intermediate,
        ),
        (
            "envelope",
            "Envelope",
            "Fixed percentage bands around a moving average",
            "volatility",
            vec!["indicator", "volatility", "envelope", "bands", "percentage"],
            Complexity::Basic,
        ),
        (
            "price_channel",
            "Price Channel",
            "Highest high and lowest low over N periods",
            "volatility",
            vec![
                "indicator",
                "volatility",
                "price_channel",
                "channel",
                "high_low",
            ],
            Complexity::Basic,
        ),
        // ── Volume ─────────────────────────────────────────────────────
        (
            "obv",
            "On-Balance Volume (OBV)",
            "Cumulative volume based on price direction — volume trend",
            "volume",
            vec!["indicator", "volume", "obv", "cumulative", "trend"],
            Complexity::Basic,
        ),
        (
            "vwap",
            "Volume Weighted Average Price (VWAP)",
            "Average price weighted by volume — intraday fair value",
            "volume",
            vec!["indicator", "volume", "vwap", "average", "intraday"],
            Complexity::Basic,
        ),
        (
            "volume_profile",
            "Volume Profile",
            "Volume distribution at price levels — POC, value area",
            "volume",
            vec!["indicator", "volume", "volume_profile", "poc", "value_area"],
            Complexity::Advanced,
        ),
        (
            "ad",
            "Accumulation/Distribution (A/D)",
            "Money flow multiplier × volume — accumulation vs distribution",
            "volume",
            vec!["indicator", "volume", "ad", "accumulation", "distribution"],
            Complexity::Intermediate,
        ),
        (
            "cmf",
            "Chaikin Money Flow (CMF)",
            "Volume-weighted accumulation/distribution over N periods",
            "volume",
            vec!["indicator", "volume", "cmf", "money_flow", "chaikin"],
            Complexity::Intermediate,
        ),
        (
            "force_index",
            "Force Index",
            "Price change × volume — directional force",
            "volume",
            vec!["indicator", "volume", "force", "directional", "volume"],
            Complexity::Intermediate,
        ),
        (
            "eom",
            "Ease of Movement (EoM)",
            "Measures price movement relative to volume",
            "volume",
            vec![
                "indicator",
                "volume",
                "eom",
                "ease_of_movement",
                "price_volume",
            ],
            Complexity::Intermediate,
        ),
        (
            "kvo",
            "Klinger Volume Oscillator (KVO)",
            "Volume-based oscillator comparing trends in volume flow",
            "volume",
            vec!["indicator", "volume", "kvo", "oscillator", "trend"],
            Complexity::Advanced,
        ),
        (
            "mfi_indicator",
            "Money Flow Index (Volume)",
            "Volume-weighted RSI variant for volume momentum",
            "volume",
            vec!["indicator", "volume", "mfi", "volume", "flow"],
            Complexity::Intermediate,
        ),
        (
            "nvi",
            "Negative Volume Index (NVI)",
            "Tracks price on down-volume days — institutional activity",
            "volume",
            vec!["indicator", "volume", "nvi", "institutional", "down_volume"],
            Complexity::Intermediate,
        ),
        (
            "pvi",
            "Positive Volume Index (PVI)",
            "Tracks price on up-volume days — retail activity",
            "volume",
            vec!["indicator", "volume", "pvi", "retail", "up_volume"],
            Complexity::Intermediate,
        ),
        (
            "vroc",
            "Volume Rate of Change (VROC)",
            "Percentage change in volume over N periods",
            "volume",
            vec![
                "indicator",
                "volume",
                "vroc",
                "rate_of_change",
                "percentage",
            ],
            Complexity::Basic,
        ),
        (
            "vwmacd",
            "Volume Weighted MACD",
            "MACD weighted by volume — volume-confirmed momentum",
            "volume",
            vec!["indicator", "volume", "vwmacd", "macd", "volume_weighted"],
            Complexity::Advanced,
        ),
        // ── Support/Resistance ─────────────────────────────────────────
        (
            "pivot_standard",
            "Pivot Points (Standard)",
            "Classic floor-trader pivots — S1/S2/S3 and R1/R2/R3",
            "support_resistance",
            vec!["indicator", "support", "resistance", "pivot", "standard"],
            Complexity::Basic,
        ),
        (
            "pivot_fibonacci",
            "Pivot Points (Fibonacci)",
            "Fibonacci-ratio based pivot levels",
            "support_resistance",
            vec!["indicator", "support", "resistance", "pivot", "fibonacci"],
            Complexity::Basic,
        ),
        (
            "pivot_woodie",
            "Pivot Points (Woodie)",
            "Woodie's pivot formula — emphasizes closing price",
            "support_resistance",
            vec!["indicator", "support", "resistance", "pivot", "woodie"],
            Complexity::Basic,
        ),
        (
            "pivot_camarilla",
            "Pivot Points (Camarilla)",
            "Camarilla pivots for intraday reversals",
            "support_resistance",
            vec!["indicator", "support", "resistance", "pivot", "camarilla"],
            Complexity::Intermediate,
        ),
        (
            "pivot_demark",
            "Pivot Points (DeMark)",
            "Conditional pivots based on open/close relationship",
            "support_resistance",
            vec!["indicator", "support", "resistance", "pivot", "demark"],
            Complexity::Intermediate,
        ),
        (
            "fib_retracement",
            "Fibonacci Retracement",
            "23.6%, 38.2%, 50%, 61.8%, 78.6% levels",
            "support_resistance",
            vec![
                "indicator",
                "support",
                "resistance",
                "fibonacci",
                "retracement",
            ],
            Complexity::Basic,
        ),
        (
            "fib_extension",
            "Fibonacci Extension",
            "127.2%, 161.8%, 261.8% projection levels",
            "support_resistance",
            vec![
                "indicator",
                "support",
                "resistance",
                "fibonacci",
                "extension",
            ],
            Complexity::Intermediate,
        ),
        (
            "fib_fan",
            "Fibonacci Fan",
            "Diagonal support/resistance from Fibonacci ratios",
            "support_resistance",
            vec![
                "indicator",
                "support",
                "resistance",
                "fibonacci",
                "fan",
                "diagonal",
            ],
            Complexity::Intermediate,
        ),
        (
            "fib_arc",
            "Fibonacci Arc",
            "Curved support/resistance levels combining time and price",
            "support_resistance",
            vec![
                "indicator",
                "support",
                "resistance",
                "fibonacci",
                "arc",
                "time",
            ],
            Complexity::Advanced,
        ),
        (
            "gann_fan",
            "Gann Fan",
            "Diagonal lines from Gann angles — geometric support/resistance",
            "support_resistance",
            vec![
                "indicator",
                "support",
                "resistance",
                "gann",
                "fan",
                "geometric",
            ],
            Complexity::Advanced,
        ),
        (
            "gann_grid",
            "Gann Grid",
            "Grid of equidistant Gann angles across price range",
            "support_resistance",
            vec![
                "indicator",
                "support",
                "resistance",
                "gann",
                "grid",
                "geometric",
            ],
            Complexity::Expert,
        ),
        // ── Pattern ────────────────────────────────────────────────────
        (
            "head_shoulders",
            "Head & Shoulders",
            "Reversal pattern with three peaks — middle highest",
            "pattern",
            vec!["indicator", "pattern", "reversal", "head_shoulders"],
            Complexity::Intermediate,
        ),
        (
            "double_top",
            "Double Top",
            "Bearish reversal — two peaks at same level",
            "pattern",
            vec!["indicator", "pattern", "reversal", "double_top", "bearish"],
            Complexity::Basic,
        ),
        (
            "double_bottom",
            "Double Bottom",
            "Bullish reversal — two troughs at same level",
            "pattern",
            vec![
                "indicator",
                "pattern",
                "reversal",
                "double_bottom",
                "bullish",
            ],
            Complexity::Basic,
        ),
        (
            "triple_top",
            "Triple Top",
            "Bearish reversal — three peaks at same level",
            "pattern",
            vec!["indicator", "pattern", "reversal", "triple_top", "bearish"],
            Complexity::Intermediate,
        ),
        (
            "triple_bottom",
            "Triple Bottom",
            "Bullish reversal — three troughs at same level",
            "pattern",
            vec![
                "indicator",
                "pattern",
                "reversal",
                "triple_bottom",
                "bullish",
            ],
            Complexity::Intermediate,
        ),
        (
            "cup_handle",
            "Cup & Handle",
            "Bullish continuation — rounded bottom with short pullback",
            "pattern",
            vec![
                "indicator",
                "pattern",
                "continuation",
                "cup_handle",
                "bullish",
            ],
            Complexity::Intermediate,
        ),
        (
            "wedge",
            "Wedge",
            "Converging trendlines — rising wedge bearish, falling wedge bullish",
            "pattern",
            vec!["indicator", "pattern", "reversal", "wedge", "converging"],
            Complexity::Intermediate,
        ),
        (
            "flag",
            "Flag",
            "Brief consolidation after strong move — continuation pattern",
            "pattern",
            vec![
                "indicator",
                "pattern",
                "continuation",
                "flag",
                "consolidation",
            ],
            Complexity::Basic,
        ),
        (
            "pennant",
            "Pennant",
            "Symmetrical convergence after sharp move — continuation",
            "pattern",
            vec![
                "indicator",
                "pattern",
                "continuation",
                "pennant",
                "converging",
            ],
            Complexity::Basic,
        ),
        (
            "triangle",
            "Triangle",
            "Converging trendlines — ascending, descending, or symmetrical",
            "pattern",
            vec![
                "indicator",
                "pattern",
                "continuation",
                "triangle",
                "converging",
            ],
            Complexity::Basic,
        ),
        (
            "rectangle",
            "Rectangle",
            "Horizontal support/resistance range — consolidation",
            "pattern",
            vec!["indicator", "pattern", "continuation", "rectangle", "range"],
            Complexity::Basic,
        ),
        (
            "rounding_bottom",
            "Rounding Bottom",
            "Gradual reversal forming a U-shape — accumulation",
            "pattern",
            vec![
                "indicator",
                "pattern",
                "reversal",
                "rounding_bottom",
                "accumulation",
            ],
            Complexity::Intermediate,
        ),
        (
            "v_pattern",
            "V-Pattern",
            "Sharp reversal — quick sell-off followed by equally quick recovery",
            "pattern",
            vec!["indicator", "pattern", "reversal", "v_pattern", "sharp"],
            Complexity::Basic,
        ),
        (
            "diamond",
            "Diamond",
            "Broadening then narrowing price action — rare reversal pattern",
            "pattern",
            vec!["indicator", "pattern", "reversal", "diamond", "rare"],
            Complexity::Advanced,
        ),
        // ── Custom / Composite ─────────────────────────────────────────
        (
            "ichimoku",
            "Ichimoku Cloud",
            "Multi-component trend system — Kumo, Tenkan, Kijun, Chikou, Senkou",
            "custom",
            vec![
                "indicator",
                "custom",
                "ichimoku",
                "cloud",
                "trend",
                "multi_component",
            ],
            Complexity::Advanced,
        ),
        (
            "parabolic_sar",
            "Parabolic SAR",
            "Parabolic stop-and-reverse — trailing stop for trends",
            "custom",
            vec!["indicator", "custom", "parabolic", "sar", "trailing_stop"],
            Complexity::Intermediate,
        ),
        (
            "adx_di",
            "ADX / DI+ / DI-",
            "Average Directional Index with Directional Indicators — trend strength",
            "custom",
            vec![
                "indicator",
                "custom",
                "adx",
                "directional",
                "trend_strength",
            ],
            Complexity::Intermediate,
        ),
        (
            "vortex",
            "Vortex Indicator (VI)",
            "Positive and negative vortex — directional trend detection",
            "custom",
            vec!["indicator", "custom", "vortex", "directional", "trend"],
            Complexity::Intermediate,
        ),
        (
            "supertrend",
            "Supertrend",
            "ATR-based overlay — trend direction with entry/exit levels",
            "custom",
            vec!["indicator", "custom", "supertrend", "atr", "trend"],
            Complexity::Intermediate,
        ),
        (
            "psar",
            "Parabolic SAR (PSAR)",
            "Discrete parabolic stop-and-reverse — dot-based trend",
            "custom",
            vec!["indicator", "custom", "psar", "parabolic", "dot"],
            Complexity::Intermediate,
        ),
        (
            "atr_trailing_stop",
            "ATR Trailing Stop",
            "ATR multiple trailing stop for trend exits",
            "custom",
            vec![
                "indicator",
                "custom",
                "atr_trailing",
                "trailing_stop",
                "atr",
            ],
            Complexity::Intermediate,
        ),
        (
            "bollinger_squeeze",
            "Bollinger Squeeze",
            "Detects low volatility expansion setups — breakout anticipation",
            "custom",
            vec!["indicator", "custom", "squeeze", "bollinger", "breakout"],
            Complexity::Advanced,
        ),
        (
            "rsi_divergence",
            "RSI Divergence",
            "Detects bullish/bearish divergence between RSI and price",
            "custom",
            vec!["indicator", "custom", "rsi", "divergence", "momentum"],
            Complexity::Advanced,
        ),
        (
            "macd_histogram",
            "MACD Histogram",
            "Visual representation of MACD line minus signal line",
            "custom",
            vec!["indicator", "custom", "macd", "histogram", "momentum"],
            Complexity::Basic,
        ),
        (
            "stoch_rsi",
            "Stochastic RSI",
            "Stochastic applied to RSI — double smooth momentum",
            "custom",
            vec!["indicator", "custom", "stochastic", "rsi", "momentum"],
            Complexity::Intermediate,
        ),
        (
            "elder_ray",
            "Elder Ray (Bull/Bear Power)",
            "Measures buying and selling pressure relative to EMA",
            "custom",
            vec!["indicator", "custom", "elder", "bull_bear", "pressure"],
            Complexity::Intermediate,
        ),
        (
            "chaikin_oscillator",
            "Chaikin Oscillator",
            "MACD of A/D line — money flow momentum",
            "custom",
            vec!["indicator", "custom", "chaikin", "oscillator", "money_flow"],
            Complexity::Intermediate,
        ),
        (
            "mass_index",
            "Mass Index",
            "Measures range expansion and contraction — reversal predictor",
            "custom",
            vec!["indicator", "custom", "mass", "range", "reversal"],
            Complexity::Advanced,
        ),
        (
            "vhf",
            "Vertical Horizontal Filter (VHF)",
            "Measures trend strength vs ranging conditions",
            "custom",
            vec!["indicator", "custom", "vhf", "trend", "range"],
            Complexity::Intermediate,
        ),
    ];

    for (id, name, desc, subcat, tags, complexity) in indicators {
        registry.register(ToolEntry {
            id: format!("indicator_{}", id),
            name: name.to_string(),
            category: Category::Indicator,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: Implementation::BuiltIn,
        });
    }
}
