use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let tools = vec![
        ("coindesk", "CoinDesk News Feed", "Leading crypto news — comprehensive coverage of market events", "crypto",
         vec!["news", "coindesk", "crypto", "comprehensive"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.coindesk.com/arc/outboundfeeds/rss".into() }),
        ("cointelegraph", "Cointelegraph Feed", "Crypto news with technical analysis focus", "crypto",
         vec!["news", "cointelegraph", "crypto", "analysis"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://cointelegraph.com/rss".into() }),
        ("the_block", "The Block Research", "Institutional-grade crypto research and news", "crypto",
         vec!["news", "the-block", "research", "institutional"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://www.theblock.co/rss.xml".into() }),
        ("decrypt", "Decrypt News", "Web3, DeFi, NFT news — accessible crypto journalism", "crypto",
         vec!["news", "decrypt", "web3", "defi"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://decrypt.co/feed".into() }),
        ("reuters_finance", "Reuters Finance Feed", "Global financial news — markets, economy, geopolitics", "finance",
         vec!["news", "reuters", "global", "markets"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.reuters.com/markets".into() }),
        ("bloomberg_markets", "Bloomberg Markets", "Professional financial news and analysis", "finance",
         vec!["news", "bloomberg", "professional", "analysis"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://feeds.bloomberg.com/markets/news.rss".into() }),
        ("cnbc_finance", "CNBC Finance Feed", "US financial markets news — earnings, economic data", "finance",
         vec!["news", "cnbc", "us-markets", "earnings"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000664".into() }),
        ("seeking_alpha", "Seeking Alpha", "In-depth stock analysis and earnings coverage", "equity",
         vec!["news", "seeking-alpha", "stocks", "analysis"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://seekingalpha.com/market_currents.xml".into() }),
        ("zerohedge", "ZeroHedge Feed", "Contrarian financial commentary — alternative macro analysis", "macro",
         vec!["news", "zerohedge", "contrarian", "macro"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://feeds.feedburner.com/zerohedge/feed".into() }),
        ("forexlive", "ForexLive News", "Real-time forex market news — central bank decisions, economic data", "forex",
         vec!["news", "forexlive", "forex", "central-bank"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.forexlive.com/feed".into() }),
        ("fx_street", "FXStreet Analysis", "Forex technical and fundamental analysis", "forex",
         vec!["news", "fxstreet", "forex", "analysis"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.fxstreet.com/rss/news".into() }),
        ("economic_calendar", "Economic Calendar Events", "High-impact economic events — FOMC, NFP, CPI, GDP releases", "macro",
         vec!["news", "calendar", "economic", "macro"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://nfs.faireconomy.media/ff_calendar_thisweek.json".into() }),
        ("fed_calendar", "Federal Reserve Calendar", "FOMC meetings, speeches, minutes — monetary policy events", "macro",
         vec!["news", "fed", "fomc", "monetary-policy"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.federalreserve.gov/json/ne-press.json".into() }),
        ("earnings_calendar", "Earnings Calendar", "Upcoming earnings reports — market-moving catalyst detection", "equity",
         vec!["news", "earnings", "calendar", "catalyst"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://www.earningswhispers.com/calendar".into() }),
        ("sec_filings", "SEC EDGAR Filings", "13F, 10-K, 8-K, insider trading forms — regulatory data", "equity",
         vec!["news", "sec", "filings", "regulatory"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://efts.sec.gov/LATEST/search-index?q=".into() }),
    ];

    for (id, name, desc, subcat, tags, complexity, impl_) in tools {
        registry.register(ToolEntry {
            id: format!("news_{}", id),
            name: name.to_string(),
            category: Category::NewsSource,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: impl_,
        });
    }
}
