use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let tools = vec![
        ("mvrv", "MVRV Z-Score", "Market Value to Realized Value — identifies overvalued/undervalued zones", "valuation",
         vec!["onchain", "mvrv", "valuation", "bitcoin"], Complexity::Intermediate),
        ("sopr", "SOPR (Spent Output Profit Ratio)", "Are coins being spent in profit or loss — above 1 = profit taking", "behavior",
         vec!["onchain", "sopr", "profit", "spending"], Complexity::Intermediate),
        ("nvt", "NVT Ratio", "Network Value to Transactions — Bitcoin's P/E ratio analog", "valuation",
         vec!["onchain", "nvt", "valuation", "fundamental"], Complexity::Intermediate),
        ("nvt_signal", "NVT Signal", "Smoothed NVT — better for spotting regime changes than raw NVT", "valuation",
         vec!["onchain", "nvt-signal", "smoothed", "regime"], Complexity::Intermediate),
        ("hash_ribbons", "Hash Ribbons", "30-day and 60-day MA of hash rate — miner capitulation = buy signal", "mining",
         vec!["onchain", "hash-ribbons", "mining", "capitulation"], Complexity::Basic),
        ("puell_multiple", "Puell Multiple", "Daily coin issuance in USD terms — above 4 = overheated, below 0.5 = bottom", "mining",
         vec!["onchain", "puell", "mining", "issuance"], Complexity::Basic),
        ("stock_to_flow", "Stock-to-Flow Model", "Scarcity-based valuation — supply reduction (halvings) drives price", "valuation",
         vec!["onchain", "stock-to-flow", "scarcity", "halving"], Complexity::Advanced),
        ("thermocap_multiple", "Thermocap Multiple", "Market cap / cumulative mining revenue — miner revenue vs market valuation", "mining",
         vec!["onchain", "thermocap", "mining", "valuation"], Complexity::Intermediate),
        ("exchange_inflow", "Exchange Inflow Volume", "BTC/ETH moving TO exchanges — potential selling pressure building", "flow",
         vec!["onchain", "exchange-inflow", "flow", "selling"], Complexity::Basic),
        ("exchange_outflow", "Exchange Outflow Volume", "BTC/ETH moving FROM exchanges — accumulation / cold storage", "flow",
         vec!["onchain", "exchange-outflow", "flow", "accumulation"], Complexity::Basic),
        ("miner_revenue", "Miner Revenue Trend", "Total miner revenue from fees + block rewards — health indicator", "mining",
         vec!["onchain", "miner-revenue", "mining", "fees"], Complexity::Basic),
        ("active_addresses", "Active Addresses", "Number of unique active addresses — network usage and adoption metric", "network",
         vec!["onchain", "active-addresses", "network", "adoption"], Complexity::Basic),
        ("transaction_count", "Transaction Count", "Daily transaction volume — network activity indicator", "network",
         vec!["onchain", "transaction-count", "network", "activity"], Complexity::Basic),
        ("average_fee", "Average Transaction Fee", "Fee market dynamics — high fees indicate congestion and demand", "network",
         vec!["onchain", "fee", "network", "congestion"], Complexity::Basic),
        ("realized_cap", "Realized Capitalization", "Sum of all coins at last movement price — aggregate cost basis", "valuation",
         vec!["onchain", "realized-cap", "valuation", "cost-basis"], Complexity::Intermediate),
        ("net_unrealized_pnl", "Net Unrealized P/L (NUPL)", "Aggregate unrealized profit/loss — top/bottom zone detection", "behavior",
         vec!["onchain", "nupl", "unrealized", "pnl"], Complexity::Intermediate),
        ("reserve_risk", "Reserve Risk", "Confidence vs price — long-term holder conviction relative to price", "behavior",
         vec!["onchain", "reserve-risk", "conviction", "long-term"], Complexity::Advanced),
        ("coin_days_destroyed", "Coin Days Destroyed", "Volume of old coins moving — large CDD spikes = long-term holder selling", "behavior",
         vec!["onchain", "coin-days", "long-term", "selling"], Complexity::Intermediate),
        ("hodl_wave", "HODL Waves", "Distribution of coins by age — aging = accumulation, younging = spending", "behavior",
         vec!["onchain", "hodl-waves", "age-distribution", "holding"], Complexity::Advanced),
        ("defi_tvl", "DeFi Total Value Locked", "Aggregate TVL across DeFi protocols — ecosystem health indicator", "defi",
         vec!["onchain", "defi", "tvl", "locked"], Complexity::Basic),
        ("defi_yield", "DeFi Yield Rates", "Lending/borrowing/staking rates — yield farming opportunities", "defi",
         vec!["onchain", "defi", "yield", "farming"], Complexity::Basic),
        ("gas_price_eth", "Ethereum Gas Price", "Network congestion indicator — low gas = good entry for on-chain actions", "network",
         vec!["onchain", "gas", "ethereum", "congestion"], Complexity::Basic),
        ("staking_ratio", "Staking Participation Rate", "% of supply staked — high staking = reduced circulating supply", "network",
         vec!["onchain", "staking", "supply", "participation"], Complexity::Basic),
        ("validator_queue", "Validator Activation Queue", "Pending validators — network security and decentralization health", "network",
         vec!["onchain", "validator", "staking", "security"], Complexity::Basic),
    ];

    for (id, name, desc, subcat, tags, complexity) in tools {
        registry.register(ToolEntry {
            id: format!("onchain_{}", id),
            name: name.to_string(),
            category: Category::OnChainTool,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: Implementation::BuiltIn,
        });
    }
}
