use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let tools = vec![
        ("fear_greed_crypto", "Crypto Fear & Greed Index", "0-100 composite score from volatility, momentum, social, volume, dominance", "composite",
         vec!["sentiment", "fear-greed", "crypto", "composite"], Complexity::Basic),
        ("fear_greed_stock", "CNN Fear & Greed Index", "7 indicators: put/call, market breadth, VIX, safe haven, junk bond, momentum, breadth", "composite",
         vec!["sentiment", "fear-greed", "stocks", "composite"], Complexity::Basic),
        ("twitter_sentiment", "Twitter/X Sentiment Score", "NLP analysis of crypto/stock mentions — bullish/bearish/neutral classification", "social",
         vec!["sentiment", "twitter", "social", "nlp"], Complexity::Intermediate),
        ("reddit_sentiment", "Reddit Sentiment Score", "WallStreetBets, r/cryptocurrency, r/investing sentiment analysis", "social",
         vec!["sentiment", "reddit", "social", "community"], Complexity::Intermediate),
        ("telegram_sentiment", "Telegram Group Sentiment", "Crypto group sentiment — large groups can signal retail crowd positioning", "social",
         vec!["sentiment", "telegram", "social", "retail"], Complexity::Intermediate),
        ("social_dominance", "Social Dominance Score", "Share of social media conversation for specific asset — rising = potential top", "social",
         vec!["sentiment", "dominance", "social", "contrarian"], Complexity::Basic),
        ("google_trends", "Google Trends Score", "Search volume trends — rising search = potential FOMO top or capitulation bottom", "search",
         vec!["sentiment", "google", "search", "trends"], Complexity::Basic),
        ("news_sentiment_nlp", "NLP News Sentiment", "Transformer-based sentiment classification of financial news headlines", "nlp",
         vec!["sentiment", "nlp", "news", "transformer"], Complexity::Advanced),
        ("earnings_sentiment", "Earnings Call Sentiment", "NLP analysis of earnings transcripts — management tone shift detection", "nlp",
         vec!["sentiment", "earnings", "nlp", "transcripts"], Complexity::Expert),
        ("insider_sentiment", "Insider Trading Sentiment", "Aggregate insider buy/sell ratios — SEC Form 4 data analysis", "fundamental",
         vec!["sentiment", "insider", "sec", "fundamental"], Complexity::Intermediate),
        ("analyst_consensus", "Analyst Consensus Score", "Aggregate analyst ratings — buy/hold/sell distribution, target price consensus", "fundamental",
         vec!["sentiment", "analyst", "consensus", "fundamental"], Complexity::Basic),
        ("fund_flow", "Fund Flow Indicator", "ETF and mutual fund inflows/outflows — institutional positioning signal", "institutional",
         vec!["sentiment", "fund-flow", "etf", "institutional"], Complexity::Intermediate),
        ("short_interest", "Short Interest Ratio", "Days to cover + short interest percentage — squeeze potential", "equity",
         vec!["sentiment", "short-interest", "squeeze", "equity"], Complexity::Basic),
        ("put_call_ratio", "Put/Call Ratio", "Options sentiment — high ratio = bearish, contrarian buy signal at extremes", "options",
         vec!["sentiment", "put-call", "options", "contrarian"], Complexity::Basic),
        ("vix_term_structure", "VIX Term Structure", "Volatility regime indicator — contango vs backwardation signals fear", "volatility",
         vec!["sentiment", "vix", "term-structure", "volatility"], Complexity::Intermediate),
        ("credit_spread", "Credit Spread Indicator", "Corporate bond spread — widening = risk-off, tightening = risk-on", "macro",
         vec!["sentiment", "credit-spread", "bonds", "macro"], Complexity::Intermediate),
        ("gold_ratio", "Gold/Silver Ratio", "Historical safe-haven signal — extreme readings indicate regime shifts", "macro",
         vec!["sentiment", "gold-silver", "safe-haven", "ratio"], Complexity::Basic),
        ("dxy_momentum", "DXY Momentum", "US Dollar Index trend — strong dollar = risk-off for emerging markets", "macro",
         vec!["sentiment", "dollar", "dxy", "macro"], Complexity::Basic),
        ("yield_curve", "Yield Curve Shape", "2s10s or 3m10y spread — inversion historically precedes recessions", "macro",
         vec!["sentiment", "yield-curve", "recession", "macro"], Complexity::Intermediate),
        ("crypto_funding", "Crypto Funding Rate", "Perpetual futures funding rate — positive = longs pay shorts, overheated", "crypto",
         vec!["sentiment", "funding-rate", "perpetuals", "crypto"], Complexity::Basic),
        ("long_short_ratio", "Long/Short Ratio", "Exchange-wide long vs short positioning — extreme = reversal signal", "crypto",
         vec!["sentiment", "long-short", "positioning", "crypto"], Complexity::Basic),
        ("open_interest_change", "Open Interest Change", "Rapid OI increase = new money entering — potential breakout or breakdown", "crypto",
         vec!["sentiment", "open-interest", "derivatives", "crypto"], Complexity::Basic),
        ("liquidation_cascade", "Liquidation Cascade Detector", "Track leveraged positions approaching liquidation — cascade potential", "crypto",
         vec!["sentiment", "liquidation", "cascade", "leverage"], Complexity::Advanced),
        ("stablecoin_flow", "Stablecoin Flow Analysis", "USDT/USDC mint/burn — new stablecoins = buying power entering market", "crypto",
         vec!["sentiment", "stablecoin", "flow", "buying-power"], Complexity::Intermediate),
        ("exchange_reserve", "Exchange Reserve Trend", "BTC/ETH on exchanges — declining = supply squeeze, rising = selling pressure", "onchain",
         vec!["sentiment", "exchange-reserve", "supply", "onchain"], Complexity::Intermediate),
        ("whale_accumulation", "Whale Accumulation Score", "Track large wallet accumulation patterns — smart money positioning", "onchain",
         vec!["sentiment", "whale", "accumulation", "smart-money"], Complexity::Advanced),
    ];

    for (id, name, desc, subcat, tags, complexity) in tools {
        registry.register(ToolEntry {
            id: format!("sentiment_{}", id),
            name: name.to_string(),
            category: Category::SentimentTool,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: Implementation::BuiltIn,
        });
    }
}
