use crate::registry::{Category, Complexity, Implementation, ToolEntry};

/// All agent skills available in the ecosystem
pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let skills = vec![
        // ── Market Analysis (20) ───────────────────────────────────────
        (
            "technical_analysis",
            "Technical Analysis",
            "Chart pattern recognition, indicator analysis, and price action",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "technical",
                "chart",
                "price_action",
            ],
            Complexity::Intermediate,
        ),
        (
            "fundamental_analysis",
            "Fundamental Analysis",
            "Financial statement analysis, valuation metrics, and earnings models",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "fundamental",
                "valuation",
                "earnings",
            ],
            Complexity::Advanced,
        ),
        (
            "sentiment_analysis",
            "Sentiment Analysis",
            "Social sentiment, news tone, and market psychology assessment",
            "market_analysis",
            vec!["skill", "market_analysis", "sentiment", "nlp", "psychology"],
            Complexity::Intermediate,
        ),
        (
            "on_chain_analysis",
            "On-Chain Analysis",
            "Blockchain metrics, wallet tracking, and network health indicators",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "on_chain",
                "blockchain",
                "crypto",
            ],
            Complexity::Advanced,
        ),
        (
            "macro_analysis",
            "Macro Analysis",
            "Central bank policy, economic indicators, and macro regime classification",
            "market_analysis",
            vec!["skill", "market_analysis", "macro", "economic", "regime"],
            Complexity::Expert,
        ),
        (
            "microstructure_analysis",
            "Microstructure Analysis",
            "Order book dynamics, bid-ask spread, and tick-level patterns",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "microstructure",
                "order_book",
                "tick",
            ],
            Complexity::Expert,
        ),
        (
            "order_flow_analysis",
            "Order Flow Analysis",
            "Bid-ask imbalance, trade tape analysis, and volume clusters",
            "market_analysis",
            vec!["skill", "market_analysis", "order_flow", "tape", "volume"],
            Complexity::Advanced,
        ),
        (
            "volume_analysis",
            "Volume Analysis",
            "Volume trends, accumulation/distribution, and volume profile interpretation",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "volume",
                "profile",
                "distribution",
            ],
            Complexity::Intermediate,
        ),
        (
            "volatility_analysis",
            "Volatility Analysis",
            "Realized vs implied vol, vol surface modeling, and regime detection",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "volatility",
                "implied",
                "surface",
            ],
            Complexity::Advanced,
        ),
        (
            "correlation_analysis",
            "Correlation Analysis",
            "Cross-asset correlation, correlation breaks, and regime shifts",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "correlation",
                "cross_asset",
                "regime",
            ],
            Complexity::Intermediate,
        ),
        (
            "regime_detection",
            "Regime Detection",
            "Market regime classification — trend/range/volatile using HMM or clustering",
            "market_analysis",
            vec!["skill", "market_analysis", "regime", "hmm", "clustering"],
            Complexity::Expert,
        ),
        (
            "market_breadth",
            "Market Breadth",
            "Advance/decline, new highs/lows, and participation metrics",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "breadth",
                "advance_decline",
                "participation",
            ],
            Complexity::Intermediate,
        ),
        (
            "intermarket_analysis",
            "Intermarket Analysis",
            "Cross-market relationships — equities, bonds, commodities, currencies",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "intermarket",
                "cross_market",
                "relationships",
            ],
            Complexity::Advanced,
        ),
        (
            "seasonal_analysis",
            "Seasonal Analysis",
            "Calendar effects, month-of-year, day-of-week, and holiday patterns",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "seasonal",
                "calendar",
                "effects",
            ],
            Complexity::Intermediate,
        ),
        (
            "event_study",
            "Event Study",
            "Measures price impact around specific events — earnings, splits, announcements",
            "market_analysis",
            vec!["skill", "market_analysis", "event_study", "event", "impact"],
            Complexity::Advanced,
        ),
        (
            "news_analysis",
            "News Analysis",
            "Real-time news parsing, entity extraction, and market impact scoring",
            "market_analysis",
            vec!["skill", "market_analysis", "news", "nlp", "real_time"],
            Complexity::Advanced,
        ),
        (
            "social_media_analysis",
            "Social Media Analysis",
            "Twitter/Reddit/StockTwits sentiment and trending topic detection",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "social_media",
                "trending",
                "sentiment",
            ],
            Complexity::Intermediate,
        ),
        (
            "options_flow_analysis",
            "Options Flow Analysis",
            "Unusual options activity, dark pool prints, and institutional positioning",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "options_flow",
                "dark_pool",
                "institutional",
            ],
            Complexity::Advanced,
        ),
        (
            "dark_pool_analysis",
            "Dark Pool Analysis",
            "Off-exchange volume tracking and institutional order detection",
            "market_analysis",
            vec![
                "skill",
                "market_analysis",
                "dark_pool",
                "off_exchange",
                "institutional",
            ],
            Complexity::Expert,
        ),
        (
            "insider_trading_analysis",
            "Insider Trading Analysis",
            "SEC filing parsing, insider transaction patterns, and signal generation",
            "market_analysis",
            vec!["skill", "market_analysis", "insider", "sec", "filing"],
            Complexity::Intermediate,
        ),
        // ── Risk Management (15) ───────────────────────────────────────
        (
            "position_sizing",
            "Position Sizing",
            "Kelly criterion, fixed fractional, and volatility-adjusted sizing",
            "risk_management",
            vec!["skill", "risk_management", "sizing", "kelly", "volatility"],
            Complexity::Intermediate,
        ),
        (
            "stop_loss_calculation",
            "Stop Loss Calculation",
            "ATR-based, percentage-based, and volatility-based stop levels",
            "risk_management",
            vec!["skill", "risk_management", "stop_loss", "atr", "protection"],
            Complexity::Basic,
        ),
        (
            "take_profit_optimization",
            "Take Profit Optimization",
            "Risk-reward ratio optimization and partial exit strategies",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "take_profit",
                "exit",
                "risk_reward",
            ],
            Complexity::Intermediate,
        ),
        (
            "drawdown_monitoring",
            "Drawdown Monitoring",
            "Real-time drawdown tracking, circuit breakers, and recovery metrics",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "drawdown",
                "circuit_breaker",
                "monitoring",
            ],
            Complexity::Intermediate,
        ),
        (
            "portfolio_heat_management",
            "Portfolio Heat Management",
            "Aggregate portfolio risk limits and concentration checks",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "heat",
                "concentration",
                "limits",
            ],
            Complexity::Advanced,
        ),
        (
            "correlation_risk",
            "Correlation Risk",
            "Portfolio correlation monitoring and diversification scoring",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "correlation",
                "diversification",
                "concentration",
            ],
            Complexity::Advanced,
        ),
        (
            "var_calculation",
            "VaR Calculation",
            "Value at Risk — historical, parametric, and Monte Carlo methods",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "var",
                "value_at_risk",
                "monte_carlo",
            ],
            Complexity::Advanced,
        ),
        (
            "stress_testing",
            "Stress Testing",
            "Historical scenario replay and custom stress scenarios",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "stress",
                "scenario",
                "historical",
            ],
            Complexity::Advanced,
        ),
        (
            "scenario_analysis",
            "Scenario Analysis",
            "Bull/base/bear scenario modeling with probability weights",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "scenario",
                "bull_base_bear",
                "probability",
            ],
            Complexity::Intermediate,
        ),
        (
            "tail_risk_management",
            "Tail Risk Management",
            "Extreme event protection — tail hedging and kurtosis monitoring",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "tail_risk",
                "extreme",
                "hedging",
            ],
            Complexity::Expert,
        ),
        (
            "currency_hedging",
            "Currency Hedging",
            "FX exposure management, cross-currency basis, and hedge ratios",
            "risk_management",
            vec!["skill", "risk_management", "currency", "hedging", "fx"],
            Complexity::Advanced,
        ),
        (
            "greeks_calculation",
            "Greeks Calculation",
            "Delta, gamma, theta, vega, rho computation for options",
            "risk_management",
            vec!["skill", "risk_management", "greeks", "options", "delta"],
            Complexity::Advanced,
        ),
        (
            "implied_vol_analysis",
            "Implied Volatility Analysis",
            "IV surface decomposition, skew analysis, and term structure",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "implied_vol",
                "skew",
                "term_structure",
            ],
            Complexity::Expert,
        ),
        (
            "vol_surface_analysis",
            "Volatility Surface Analysis",
            "3D vol surface modeling, arbitrage checks, and surface dynamics",
            "risk_management",
            vec!["skill", "risk_management", "vol_surface", "3d", "arbitrage"],
            Complexity::Expert,
        ),
        (
            "black_swan_detection",
            "Black Swan Detection",
            "Early warning system for extreme tail events using regime and flow data",
            "risk_management",
            vec![
                "skill",
                "risk_management",
                "black_swan",
                "tail_event",
                "early_warning",
            ],
            Complexity::Expert,
        ),
        // ── Execution (15) ─────────────────────────────────────────────
        (
            "twap",
            "TWAP",
            "Time-Weighted Average Price — even execution over time window",
            "execution",
            vec!["skill", "execution", "twap", "time_weighted", "algorithm"],
            Complexity::Intermediate,
        ),
        (
            "vwap_execution",
            "VWAP Execution",
            "Volume-Weighted Average Price — track benchmark VWAP",
            "execution",
            vec!["skill", "execution", "vwap", "volume_weighted", "benchmark"],
            Complexity::Intermediate,
        ),
        (
            "implementation_shortfall",
            "Implementation Shortfall",
            "Minimize deviation from decision price — fill vs arrival",
            "execution",
            vec![
                "skill",
                "execution",
                "shortfall",
                "arrival_price",
                "benchmark",
            ],
            Complexity::Advanced,
        ),
        (
            "iceberg_orders",
            "Iceberg Orders",
            "Hidden size orders — display small portion, repeat on fill",
            "execution",
            vec!["skill", "execution", "iceberg", "hidden", "repeating"],
            Complexity::Intermediate,
        ),
        (
            "sniper_orders",
            "Sniper Orders",
            "Liquidity detection and targeted fills at optimal prices",
            "execution",
            vec!["skill", "execution", "sniper", "liquidity", "targeted"],
            Complexity::Advanced,
        ),
        (
            "bracket_orders",
            "Bracket Orders",
            "Entry with automatic stop-loss and take-profit attached",
            "execution",
            vec!["skill", "execution", "bracket", "stop_loss", "take_profit"],
            Complexity::Basic,
        ),
        (
            "oco_orders",
            "OCO Orders",
            "One-Cancels-Other — mutually exclusive order pairs",
            "execution",
            vec!["skill", "execution", "oco", "mutual_exclusion", "order"],
            Complexity::Basic,
        ),
        (
            "trailing_stop_execution",
            "Trailing Stop",
            "Dynamic stop that follows price at configurable distance",
            "execution",
            vec!["skill", "execution", "trailing_stop", "dynamic", "adaptive"],
            Complexity::Intermediate,
        ),
        (
            "scale_in",
            "Scale In",
            "Gradual position building at multiple price levels",
            "execution",
            vec![
                "skill",
                "execution",
                "scale_in",
                "gradual",
                "position_build",
            ],
            Complexity::Basic,
        ),
        (
            "scale_out",
            "Scale Out",
            "Gradual position reduction at multiple price levels",
            "execution",
            vec![
                "skill",
                "execution",
                "scale_out",
                "gradual",
                "position_reduce",
            ],
            Complexity::Basic,
        ),
        (
            "market_order",
            "Market Order",
            "Immediate execution at best available price",
            "execution",
            vec![
                "skill",
                "execution",
                "market_order",
                "immediate",
                "aggressive",
            ],
            Complexity::Basic,
        ),
        (
            "limit_order",
            "Limit Order",
            "Execute at specified price or better",
            "execution",
            vec![
                "skill",
                "execution",
                "limit_order",
                "price_limit",
                "passive",
            ],
            Complexity::Basic,
        ),
        (
            "stop_order",
            "Stop Order",
            "Triggers market order when stop price is reached",
            "execution",
            vec!["skill", "execution", "stop_order", "trigger", "protection"],
            Complexity::Basic,
        ),
        (
            "stop_limit_order",
            "Stop-Limit Order",
            "Triggers limit order when stop price is reached",
            "execution",
            vec!["skill", "execution", "stop_limit", "trigger", "limit"],
            Complexity::Basic,
        ),
        (
            "trailing_limit_order",
            "Trailing Limit Order",
            "Limit order that adjusts with price movement",
            "execution",
            vec![
                "skill",
                "execution",
                "trailing_limit",
                "dynamic",
                "adjusting",
            ],
            Complexity::Intermediate,
        ),
        // ── Portfolio Construction (15) ────────────────────────────────
        (
            "mean_variance",
            "Mean-Variance Optimization",
            "Markowitz mean-variance efficient frontier construction",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "mean_variance",
                "markowitz",
                "efficient_frontier",
            ],
            Complexity::Advanced,
        ),
        (
            "risk_parity",
            "Risk Parity",
            "Equal risk contribution from each asset class",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "risk_parity",
                "equal_risk",
                "allocation",
            ],
            Complexity::Advanced,
        ),
        (
            "black_litterman",
            "Black-Litterman Model",
            "Market equilibrium + investor views → posterior expected returns",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "black_litterman",
                "views",
                "posterior",
            ],
            Complexity::Expert,
        ),
        (
            "equal_weight",
            "Equal Weight",
            "Equal dollar allocation across all assets",
            "portfolio_construction",
            vec!["skill", "portfolio", "equal_weight", "simple", "passive"],
            Complexity::Basic,
        ),
        (
            "minimum_variance",
            "Minimum Variance Portfolio",
            "Portfolio with lowest possible total variance",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "minimum_variance",
                "low_vol",
                "conservative",
            ],
            Complexity::Intermediate,
        ),
        (
            "maximum_diversification",
            "Maximum Diversification",
            "Maximize diversification ratio across assets",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "max_diversification",
                "diversification_ratio",
                "optimization",
            ],
            Complexity::Advanced,
        ),
        (
            "maximum_sharpe",
            "Maximum Sharpe Ratio",
            "Optimize for highest risk-adjusted return",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "max_sharpe",
                "risk_adjusted",
                "optimization",
            ],
            Complexity::Intermediate,
        ),
        (
            "hierarchical_risk_parity",
            "Hierarchical Risk Parity (HRP)",
            "Machine learning based hierarchical portfolio allocation",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "hrp",
                "hierarchical",
                "machine_learning",
            ],
            Complexity::Expert,
        ),
        (
            "kelly_optimal",
            "Kelly Criterion Optimal Allocation",
            "Mathematically optimal bet sizing for maximum long-run growth",
            "portfolio_construction",
            vec!["skill", "portfolio", "kelly", "optimal", "growth"],
            Complexity::Advanced,
        ),
        (
            "anti_martingale",
            "Anti-Martingale Strategy",
            "Increase exposure in winning positions, reduce in losers",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "anti_martingale",
                "pyramiding",
                "momentum",
            ],
            Complexity::Intermediate,
        ),
        (
            "constant_proportion",
            "Constant Proportion Portfolio Insurance (CPPI)",
            "Dynamic allocation preserving floor with upside participation",
            "portfolio_construction",
            vec!["skill", "portfolio", "cppi", "floor", "dynamic"],
            Complexity::Intermediate,
        ),
        (
            "dynamic_allocation",
            "Dynamic Asset Allocation",
            "Tactical shifts based on regime and valuation signals",
            "portfolio_construction",
            vec!["skill", "portfolio", "dynamic", "tactical", "regime"],
            Complexity::Advanced,
        ),
        (
            "asset_correlation",
            "Asset Correlation Mapping",
            "Cross-asset correlation matrix computation and monitoring",
            "portfolio_construction",
            vec!["skill", "portfolio", "correlation", "matrix", "cross_asset"],
            Complexity::Intermediate,
        ),
        (
            "rebalancing_strategy",
            "Rebalancing Strategy",
            "Calendar, threshold, or momentum-based portfolio rebalancing",
            "portfolio_construction",
            vec!["skill", "portfolio", "rebalancing", "calendar", "threshold"],
            Complexity::Intermediate,
        ),
        (
            "tax_efficient_placement",
            "Tax-Efficient Placement",
            "Asset location optimization across taxable and tax-advantaged accounts",
            "portfolio_construction",
            vec![
                "skill",
                "portfolio",
                "tax_efficient",
                "asset_location",
                "optimization",
            ],
            Complexity::Advanced,
        ),
        // ── Research (15) ──────────────────────────────────────────────
        (
            "backtest_runner",
            "Backtest Runner",
            "Full simulation engine with slippage, commissions, and fill modeling",
            "research",
            vec!["skill", "research", "backtest", "simulation", "engine"],
            Complexity::Advanced,
        ),
        (
            "walk_forward_analysis",
            "Walk-Forward Analysis",
            "Out-of-sample validation by rolling in-sample window forward",
            "research",
            vec![
                "skill",
                "research",
                "walk_forward",
                "out_of_sample",
                "validation",
            ],
            Complexity::Advanced,
        ),
        (
            "monte_carlo_simulation",
            "Monte Carlo Simulation",
            "Random path generation for strategy robustness testing",
            "research",
            vec!["skill", "research", "monte_carlo", "simulation", "random"],
            Complexity::Advanced,
        ),
        (
            "parameter_optimization",
            "Parameter Optimization",
            "Grid search, random search, and Bayesian optimization of strategy params",
            "research",
            vec![
                "skill",
                "research",
                "optimization",
                "grid_search",
                "bayesian",
            ],
            Complexity::Advanced,
        ),
        (
            "robustness_check",
            "Robustness Check",
            "Tests sensitivity of strategy to small parameter changes",
            "research",
            vec![
                "skill",
                "research",
                "robustness",
                "sensitivity",
                "stability",
            ],
            Complexity::Intermediate,
        ),
        (
            "in_sample_bias_test",
            "In-Sample Bias Test",
            "Detects overfitting by comparing in-sample vs out-of-sample performance",
            "research",
            vec!["skill", "research", "overfitting", "bias", "in_sample"],
            Complexity::Intermediate,
        ),
        (
            "regime_aware_backtest",
            "Regime-Aware Backtest",
            "Backtest with regime detection — evaluate performance across market states",
            "research",
            vec![
                "skill",
                "research",
                "regime_backtest",
                "regime",
                "conditional",
            ],
            Complexity::Expert,
        ),
        (
            "transaction_cost_model",
            "Transaction Cost Model",
            "Commission, exchange fees, and spread cost estimation",
            "research",
            vec![
                "skill",
                "research",
                "transaction_cost",
                "commission",
                "fees",
            ],
            Complexity::Intermediate,
        ),
        (
            "slippage_model",
            "Slippage Model",
            "Market impact and slippage estimation based on order size and liquidity",
            "research",
            vec![
                "skill",
                "research",
                "slippage",
                "market_impact",
                "liquidity",
            ],
            Complexity::Advanced,
        ),
        (
            "market_impact_model",
            "Market Impact Model",
            "Almgren-Chriss or square-root impact models for execution cost",
            "research",
            vec![
                "skill",
                "research",
                "market_impact",
                "execution_cost",
                "modeling",
            ],
            Complexity::Expert,
        ),
        (
            "liquidity_analysis",
            "Liquidity Analysis",
            "Market depth, time-to-fill estimation, and liquidity scoring",
            "research",
            vec!["skill", "research", "liquidity", "depth", "scoring"],
            Complexity::Advanced,
        ),
        (
            "alpha_decay",
            "Alpha Decay Analysis",
            "Measures how quickly strategy alpha degrades over time",
            "research",
            vec![
                "skill",
                "research",
                "alpha_decay",
                "degradation",
                "half_life",
            ],
            Complexity::Expert,
        ),
        (
            "factor_exposure",
            "Factor Exposure Analysis",
            "Decompose returns into known factor exposures (Fama-French, Barra)",
            "research",
            vec!["skill", "research", "factor", "fama_french", "barra"],
            Complexity::Expert,
        ),
        (
            "cross_validation",
            "Cross Validation",
            "K-fold and time-series cross-validation for strategy evaluation",
            "research",
            vec![
                "skill",
                "research",
                "cross_validation",
                "k_fold",
                "validation",
            ],
            Complexity::Intermediate,
        ),
        (
            "out_of_sample_test",
            "Out-of-Sample Test",
            "Strict walk-forward or holdout out-of-sample performance validation",
            "research",
            vec![
                "skill",
                "research",
                "out_of_sample",
                "holdout",
                "validation",
            ],
            Complexity::Intermediate,
        ),
        // ── Learning (15) ──────────────────────────────────────────────
        (
            "online_learning",
            "Online Learning",
            "Incrementally update models as new data arrives without full retrain",
            "learning",
            vec!["skill", "learning", "online", "incremental", "streaming"],
            Complexity::Advanced,
        ),
        (
            "transfer_learning",
            "Transfer Learning",
            "Apply knowledge from one market/asset to another",
            "learning",
            vec![
                "skill",
                "learning",
                "transfer",
                "cross_market",
                "pretrained",
            ],
            Complexity::Expert,
        ),
        (
            "reinforcement_learning",
            "Reinforcement Learning",
            "RL-based optimal execution and portfolio allocation",
            "learning",
            vec!["skill", "learning", "reinforcement", "rl", "optimal"],
            Complexity::Expert,
        ),
        (
            "meta_learning",
            "Meta-Learning",
            "Learn to learn — adapt quickly to new market regimes with minimal data",
            "learning",
            vec!["skill", "learning", "meta", "few_shot", "adaptive"],
            Complexity::Expert,
        ),
        (
            "ensemble_methods",
            "Ensemble Methods",
            "Combine multiple models via bagging, boosting, or stacking",
            "learning",
            vec!["skill", "learning", "ensemble", "bagging", "boosting"],
            Complexity::Intermediate,
        ),
        (
            "feature_importance",
            "Feature Importance",
            "SHAP values, permutation importance, and feature selection",
            "learning",
            vec![
                "skill",
                "learning",
                "feature_importance",
                "shap",
                "selection",
            ],
            Complexity::Intermediate,
        ),
        (
            "hyperparameter_tuning",
            "Hyperparameter Tuning",
            "Bayesian optimization, grid search, and random search",
            "learning",
            vec![
                "skill",
                "learning",
                "hyperparameter",
                "tuning",
                "optimization",
            ],
            Complexity::Intermediate,
        ),
        (
            "model_selection",
            "Model Selection",
            "Compare and select best models using AIC, BIC, or cross-validation",
            "learning",
            vec![
                "skill",
                "learning",
                "model_selection",
                "aic_bic",
                "comparison",
            ],
            Complexity::Intermediate,
        ),
        (
            "overfitting_detection",
            "Overfitting Detection",
            "Detect overfitting via learning curves, complexity analysis, and testing",
            "learning",
            vec![
                "skill",
                "learning",
                "overfitting",
                "detection",
                "generalization",
            ],
            Complexity::Intermediate,
        ),
        (
            "bias_variance_tradeoff",
            "Bias-Variance Tradeoff",
            "Diagnose and balance model complexity vs training error",
            "learning",
            vec![
                "skill",
                "learning",
                "bias_variance",
                "complexity",
                "diagnosis",
            ],
            Complexity::Intermediate,
        ),
        (
            "concept_drift",
            "Concept Drift Detection",
            "Detect when underlying data distribution changes — retrain triggers",
            "learning",
            vec![
                "skill",
                "learning",
                "concept_drift",
                "distribution_shift",
                "monitoring",
            ],
            Complexity::Advanced,
        ),
        (
            "active_learning",
            "Active Learning",
            "Select most informative samples for labeling — minimize annotation cost",
            "learning",
            vec![
                "skill",
                "learning",
                "active",
                "uncertainty_sampling",
                "labeling",
            ],
            Complexity::Advanced,
        ),
        (
            "curriculum_learning",
            "Curriculum Learning",
            "Train on easy-to-hard data ordering for faster convergence",
            "learning",
            vec!["skill", "learning", "curriculum", "ordering", "convergence"],
            Complexity::Advanced,
        ),
        (
            "self_play",
            "Self-Play",
            "Agent competes against itself to discover new strategies",
            "learning",
            vec!["skill", "learning", "self_play", "competitive", "emergent"],
            Complexity::Expert,
        ),
        (
            "adversarial_training",
            "Adversarial Training",
            "Train models to be robust against adversarial market conditions",
            "learning",
            vec!["skill", "learning", "adversarial", "robustness", "attack"],
            Complexity::Expert,
        ),
        // ── Communication (10) ─────────────────────────────────────────
        (
            "trade_journal",
            "Trade Journal",
            "Automated trade documentation with rationale and outcome tracking",
            "communication",
            vec![
                "skill",
                "communication",
                "journal",
                "documentation",
                "trade",
            ],
            Complexity::Basic,
        ),
        (
            "performance_report",
            "Performance Report",
            "Generate returns, risk metrics, attribution, and benchmark comparison",
            "communication",
            vec![
                "skill",
                "communication",
                "performance",
                "report",
                "attribution",
            ],
            Complexity::Intermediate,
        ),
        (
            "risk_report",
            "Risk Report",
            "Portfolio risk summary — VaR, drawdown, exposure breakdown",
            "communication",
            vec!["skill", "communication", "risk", "report", "var"],
            Complexity::Intermediate,
        ),
        (
            "market_brief",
            "Market Brief",
            "Daily market overview — key moves, events, and outlook",
            "communication",
            vec!["skill", "communication", "brief", "daily", "overview"],
            Complexity::Basic,
        ),
        (
            "position_summary",
            "Position Summary",
            "Current holdings with P&L, weights, and risk contributions",
            "communication",
            vec!["skill", "communication", "position", "summary", "holdings"],
            Complexity::Basic,
        ),
        (
            "alert_generation",
            "Alert Generation",
            "Condition-based alerts for price, volume, or indicator triggers",
            "communication",
            vec!["skill", "communication", "alert", "trigger", "condition"],
            Complexity::Basic,
        ),
        (
            "reasoning_documentation",
            "Reasoning Documentation",
            "Structured trade rationale with supporting evidence",
            "communication",
            vec![
                "skill",
                "communication",
                "reasoning",
                "documentation",
                "rationale",
            ],
            Complexity::Intermediate,
        ),
        (
            "decision_audit",
            "Decision Audit",
            "Complete audit trail of all trading decisions and their outcomes",
            "communication",
            vec!["skill", "communication", "audit", "trail", "decision"],
            Complexity::Intermediate,
        ),
        (
            "compliance_report",
            "Compliance Report",
            "Regulatory compliance checks and position limit reports",
            "communication",
            vec![
                "skill",
                "communication",
                "compliance",
                "regulatory",
                "limits",
            ],
            Complexity::Intermediate,
        ),
        (
            "stakeholder_update",
            "Stakeholder Update",
            "Formatted performance updates for investors and management",
            "communication",
            vec![
                "skill",
                "communication",
                "stakeholder",
                "investor",
                "update",
            ],
            Complexity::Basic,
        ),
    ];

    for (id, name, desc, subcat, tags, complexity) in skills {
        registry.register(ToolEntry {
            id: format!("skill_{}", id),
            name: name.to_string(),
            category: Category::Skill,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: Implementation::BuiltIn,
        });
    }
}
