use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let styles = vec![
        ("contrarian", "Contrarian", "Buy fear, sell greed — mean-reversion at extremes", "reversal",
         vec!["thinking", "contrarian", "value", "reversal"], Complexity::Intermediate),
        ("momentum", "Momentum", "Trend is your friend — persistence of returns from behavioral herding", "trend",
         vec!["thinking", "momentum", "trend", "persistence"], Complexity::Basic),
        ("mean_reversion", "Mean-Reversion", "Prices revert to fair value — statistical mispricing from overreaction", "reversion",
         vec!["thinking", "mean-reversion", "statistical", "fair-value"], Complexity::Intermediate),
        ("breakout", "Breakout", "Enter when price breaks key level — volatility expansion signals regime change", "breakout",
         vec!["thinking", "breakout", "volatility", "regime-change"], Complexity::Basic),
        ("scalping", "Scalping", "Many small profits, quick exits — exploits microstructure inefficiencies", "microstructure",
         vec!["thinking", "scalping", "microstructure", "high-frequency"], Complexity::Advanced),
        ("swing", "Swing Trading", "Capture multi-day moves — intermediate momentum and technical patterns", "intermediate",
         vec!["thinking", "swing", "multi-day", "technical"], Complexity::Basic),
        ("position", "Position Trading", "Long-duration macro bets — fundamental mispricing over quarters", "long-term",
         vec!["thinking", "position", "long-term", "fundamental"], Complexity::Intermediate),
        ("arbitrage", "Arbitrage", "Riskless or near-riskless profit from cross-market price discrepancies", "risk-free",
         vec!["thinking", "arbitrage", "risk-free", "cross-market"], Complexity::Advanced),
        ("stat_arb", "Statistical Arbitrage", "Model-driven convergence trades — cointegration and factor-neutral positioning", "quantitative",
         vec!["thinking", "stat-arb", "cointegration", "factor"], Complexity::Expert),
        ("pairs_trading", "Pairs Trading", "Long/short correlated assets — relative value and spread reversion", "relative-value",
         vec!["thinking", "pairs", "correlation", "spread"], Complexity::Advanced),
        ("market_making", "Market Making", "Provide liquidity, earn spread — inventory management and information advantage", "liquidity",
         vec!["thinking", "market-making", "liquidity", "spread"], Complexity::Expert),
        ("event_driven", "Event-Driven", "Trade around catalysts — earnings, M&A, restructurings, FDA decisions", "catalyst",
         vec!["thinking", "event-driven", "catalyst", "earnings"], Complexity::Intermediate),
        ("macro", "Macro Trading", "Top-down global allocation — interest rates, currencies, commodities cycles", "top-down",
         vec!["thinking", "macro", "global", "top-down"], Complexity::Expert),
        ("quantitative", "Quantitative Systematic", "Data-driven, systematic — statistical edges, automation, scale at volume", "systematic",
         vec!["thinking", "quantitative", "systematic", "data-driven"], Complexity::Advanced),
        ("value", "Value Investing", "Buy below intrinsic value — fundamentals-based with margin of safety", "fundamental",
         vec!["thinking", "value", "intrinsic", "margin-of-safety"], Complexity::Intermediate),
        ("growth", "Growth Trading", "Buy accelerating earnings — revenue growth momentum over valuation", "growth",
         vec!["thinking", "growth", "earnings", "acceleration"], Complexity::Intermediate),
        ("sentiment", "Sentiment-Driven", "Trade crowd psychology — fear/greed indexes, social media momentum, news flow", "psychology",
         vec!["thinking", "sentiment", "crowd", "psychology"], Complexity::Intermediate),
        ("volatility", "Volatility Trading", "Trade volatility itself — straddles, strangles, vol surface arbitrage", "volatility",
         vec!["thinking", "volatility", "options", "vol-surface"], Complexity::Expert),
        ("order_flow", "Order Flow Trading", "Read tape and order book — delta, absorption, iceberg detection, sweep analysis", "microstructure",
         vec!["thinking", "order-flow", "tape-reading", "book-analysis"], Complexity::Expert),
        ("seasonal", "Seasonal Patterns", "Exploit calendar effects — January effect, sell in May, options expiration cycles", "calendar",
         vec!["thinking", "seasonal", "calendar", "patterns"], Complexity::Basic),
        ("intermarket", "Intermarket Analysis", "Cross-asset relationships — bonds vs equities, USD vs commodities, rates vs sectors", "cross-asset",
         vec!["thinking", "intermarket", "cross-asset", "relationships"], Complexity::Advanced),
        ("market_profile", "Market Profile", "Volume-at-price distribution — value areas, POC, single prints, distribution shapes", "profile",
         vec!["thinking", "market-profile", "volume-profile", "value-area"], Complexity::Advanced),
        ("wyckoff", "Wyckoff Method", "Accumulation/distribution cycles — composite operator, spring, upthrust, Phase A/B/C/D/E", "structural",
         vec!["thinking", "wyckoff", "accumulation", "distribution"], Complexity::Advanced),
        ("elliott_wave", "Elliott Wave", "Impulse/corrective patterns — wave degrees, alternation, fibonacci relationships", "pattern",
         vec!["thinking", "elliott-wave", "impulse", "corrective"], Complexity::Expert),
        ("harmonic", "Harmonic Patterns", "Fibonacci-based geometric patterns — Gartley, butterfly, bat, crab, cypher", "pattern",
         vec!["thinking", "harmonic", "fibonacci", "geometric"], Complexity::Expert),
        ("vwap", "VWAP Trading", "Volume-Weighted Average Price — institutional benchmark, mean-reversion to VWAP", "institutional",
         vec!["thinking", "vwap", "institutional", "benchmark"], Complexity::Intermediate),
        ("trendline", "Trendline Trading", "Support/resistance via trendlines — breakout, retest, acceleration", "technical",
         vec!["thinking", "trendline", "support", "resistance"], Complexity::Basic),
        ("fibonacci", "Fibonacci Retracement", "Key ratios for support/resistance — 23.6%, 38.2%, 50%, 61.8%, 78.6%", "technical",
         vec!["thinking", "fibonacci", "retracement", "ratio"], Complexity::Basic),
        ("ichimoku", "Ichimoku Cloud", "Japanese chart system — tenkan, kijun, senkou spans, chikou, kumo cloud", "technical",
         vec!["thinking", "ichimoku", "japanese", "cloud"], Complexity::Advanced),
        ("dow_theory", "Dow Theory", "Market trend identification — higher highs/lows, confirmation, volume, breadth", "classical",
         vec!["thinking", "dow-theory", "classical", "trend"], Complexity::Basic),
        ("turtle", "Turtle Trading", "Systematic trend following — Donchian breakout, ATR sizing, fixed fractional", "systematic",
         vec!["thinking", "turtle", "trend-following", "systematic"], Complexity::Intermediate),
        ("peter_brandt", "Classical Charting", "Peter Brandt style — rectangles, head & shoulders, triangles with strict rules", "classical",
         vec!["thinking", "classical-charting", "pattern", "strict-rules"], Complexity::Advanced),
    ];

    for (id, name, desc, subcat, tags, complexity) in styles {
        registry.register(ToolEntry {
            id: format!("thinking_{}", id),
            name: name.to_string(),
            category: Category::ThinkingStyle,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: Implementation::BuiltIn,
        });
    }
}
