use crate::registry::{Category, Complexity, Implementation, ToolEntry};

pub fn register_all(registry: &mut super::registry::ToolRegistry) {
    let tools = vec![
        ("reqwest_http", "reqwest HTTP Client", "Rust async HTTP client — TLS, connection pooling, cookie support", "http",
         vec!["web", "http", "async", "rust-native"], Complexity::Basic,
         Implementation::CrateDependency { crate_name: "reqwest".into() }),
        ("scraper_html", "scraper HTML Parser", "CSS-selector based HTML parsing — fast, memory-efficient", "scraping",
         vec!["web", "html", "css-selector", "scraping"], Complexity::Basic,
         Implementation::CrateDependency { crate_name: "scraper".into() }),
        ("select_rs", "select.rs DOM Parser", "jQuery-like DOM querying for Rust — CSS selectors + predicates", "scraping",
         vec!["web", "dom", "jquery", "scraping"], Complexity::Basic,
         Implementation::CrateDependency { crate_name: "select".into() }),
        ("chromiumoxide", "chromiumoxide", "Headless Chrome DevTools Protocol — full browser automation", "browser",
         vec!["web", "chrome", "headless", "browser-automation"], Complexity::Advanced,
         Implementation::CrateDependency { crate_name: "chromiumoxide".into() }),
        ("playwright_rs", "playwright-rs", "Cross-browser automation — Chromium, Firefox, WebKit", "browser",
         vec!["web", "playwright", "cross-browser", "automation"], Complexity::Advanced,
         Implementation::CrateDependency { crate_name: "playwright".into() }),
        ("fantoccini", "fantoccini", "WebDriver (W3C) client for Rust — Selenium-compatible", "browser",
         vec!["web", "webdriver", "selenium", "w3c"], Complexity::Intermediate,
         Implementation::CrateDependency { crate_name: "fantoccini".into() }),
        ("rss_feed", "rss Crate", "RSS/Atom feed parser — standard format news ingestion", "feed",
         vec!["web", "rss", "atom", "news"], Complexity::Basic,
         Implementation::CrateDependency { crate_name: "rss".into() }),
        ("feed_rs", "feed-rs Crate", "RSS/Atom/JSON Feed parser — comprehensive format support", "feed",
         vec!["web", "feed", "json-feed", "comprehensive"], Complexity::Basic,
         Implementation::CrateDependency { crate_name: "feed-rs".into() }),
        ("selectolax", "selectolax", "Fast HTML parser with Modest/Lexbor backends — 10x faster than scraper", "scraping",
         vec!["web", "html", "fast", "lexbor"], Complexity::Basic,
         Implementation::CrateDependency { crate_name: "selectolax".into() }),
        ("scraperhead", "ScraperAPI", "Web scraping API — handles proxies, CAPTCHAs, JS rendering", "scraping-api",
         vec!["web", "api", "proxy", "captcha"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.scraperapi.com".into() }),
        ("brightdata", "Bright Data WebUnlocker", "Enterprise web data — unlock any page, real browser IPs", "scraping-api",
         vec!["web", "enterprise", "proxy", "unblock"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://brightdata.com/cp/api".into() }),
        ("jina_reader", "Jina Reader API", "URL to Markdown/JSON — AI-friendly web content extraction", "extraction",
         vec!["web", "markdown", "ai", "extraction"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://r.jina.ai".into() }),
        ("firecrawl", "Firecrawl API", "Crawl entire websites — extract structured data for LLM training", "crawling",
         vec!["web", "crawl", "structured", "llm"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.firecrawl.dev".into() }),
        ("crawl4ai", "Crawl4AI", "Open-source web crawler for AI — markdown output, stealth mode", "crawling",
         vec!["web", "crawl", "open-source", "ai"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://github.com/unclecode/crawl4ai".into() }),
        ("httpx_probe", "httpx (projectdiscovery)", "Fast HTTP probing — technology detection, status codes, titles", "probing",
         vec!["web", "probe", "technology-detection", "http"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://github.com/projectdiscovery/httpx".into() }),
        ("wayback", "Wayback Machine API", "Internet Archive snapshots — historical web page content", "archive",
         vec!["web", "archive", "historical", "wayback"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://web.archive.org/web/*/".into() }),
        ("corpus_api", "Common Crawl", "Massive web corpus — petabytes of raw web data for analysis", "corpus",
         vec!["web", "crawl", "massive", "dataset"], Complexity::Expert,
         Implementation::HttpEndpoint { url: "https://index.commoncrawl.org".into() }),
        ("warc_rs", "WARC Parser", "Read Web ARChive files — parse Common Crawl data in Rust", "archive",
         vec!["web", "warc", "common-crawl", "parser"], Complexity::Advanced,
         Implementation::CrateDependency { crate_name: "warc".into() }),
        ("markdownify", "html2text / markdownify", "Convert HTML to clean text/markdown — for LLM context extraction", "extraction",
         vec!["web", "html-to-text", "markdown", "extraction"], Complexity::Basic,
         Implementation::CrateDependency { crate_name: "html2text".into() }),
        ("openai_compat", "OpenAI Compatible API", "Chat completion API — works with Ollama, vLLM, any OpenAI-compatible server", "ai",
         vec!["web", "ai", "llm", "openai-compat"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "http://localhost:11434/v1".into() }),
        ("huggingface_api", "HuggingFace Inference API", "100K+ ML models — NLP, embeddings, classification, generation", "ai",
         vec!["web", "huggingface", "ml", "models"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api-inference.huggingface.co/models".into() }),
        ("cohere_api", "Cohere API", "Language models — classify, embed, generate, rerank", "ai",
         vec!["web", "cohere", "nlp", "embeddings"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.cohere.ai/v1".into() }),
        ("perplexity_api", "Perplexity API", "Real-time web-connected LLM — search-augmented generation", "ai",
         vec!["web", "perplexity", "search-augmented", "real-time"], Complexity::Intermediate,
         Implementation::HttpEndpoint { url: "https://api.perplexity.ai".into() }),
        ("telegram_bot", "Telegram Bot API", "Send alerts, receive commands — rat-tui integration for notifications", "notification",
         vec!["web", "telegram", "bot", "alerts"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://api.telegram.org/bot<token>".into() }),
        ("discord_webhook", "Discord Webhook", "Post trade alerts to Discord channels — rich embeds with trade data", "notification",
         vec!["web", "discord", "webhook", "alerts"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://discord.com/api/webhooks".into() }),
        ("slack_webhook", "Slack Webhook", "Post to Slack channels — trade notifications and alerts", "notification",
         vec!["web", "slack", "webhook", "alerts"], Complexity::Basic,
         Implementation::HttpEndpoint { url: "https://hooks.slack.com/services".into() }),
        ("email_smtp", "Email SMTP Sender", "Send trade alerts via email — supports Gmail, SendGrid, SES", "notification",
         vec!["web", "email", "smtp", "alerts"], Complexity::Basic,
         Implementation::BuiltIn),
    ];

    for (id, name, desc, subcat, tags, complexity, impl_) in tools {
        registry.register(ToolEntry {
            id: format!("web_{}", id),
            name: name.to_string(),
            category: Category::WebTool,
            description: desc.to_string(),
            subcategory: subcat.to_string(),
            complexity,
            tags: tags.into_iter().map(String::from).collect(),
            implementation: impl_,
        });
    }
}
