use serde::{Deserialize, Serialize};

/// The core event type for the rat trading system's pub-sub event bus.
///
/// Each variant wraps a strongly-typed payload so consumers can match
/// on the variant and access typed fields without manual deserialization.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RatEvent {
    /// A trade signal generated by the pipeline (BUY/SELL/HOLD).
    Signal(SignalEvent),
    /// A live market price tick for a symbol.
    MarketPrice(MarketPriceEvent),
    /// A periodic portfolio snapshot (equity, cash, P&L).
    PortfolioSnapshot(PortfolioSnapshotEvent),
    /// A health check event for a system service.
    Health(HealthEvent),
    /// A system control command (START, STOP, RESTART).
    SystemControl(SystemControlEvent),
}

// ── SignalEvent ────────────────────────────────────────────────────────────

/// A trade signal emitted by the pipeline after all guards pass.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalEvent {
    pub symbol: String,
    pub action: String, // "BUY" | "SELL" | "HOLD"
    pub entry_price: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub confidence: f64,
    pub reasoning: String,
    pub source: String,
    pub timestamp_micros: i64,
}

// ── MarketPriceEvent ───────────────────────────────────────────────────────

/// A single price tick for a symbol from an exchange.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketPriceEvent {
    pub symbol: String,
    pub price: f64,
    pub exchange: String,
    pub timestamp_micros: i64,
}

// ── PortfolioSnapshotEvent ─────────────────────────────────────────────────

/// Periodic portfolio summary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PortfolioSnapshotEvent {
    pub total_equity: f64,
    pub cash_balance: f64,
    pub daily_pnl: f64,
    pub timestamp_micros: i64,
}

// ── HealthEvent ────────────────────────────────────────────────────────────

/// Health status of a background service.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HealthEvent {
    pub service: String,
    pub healthy: bool,
    pub latency_ms: Option<u64>,
    pub timestamp_micros: i64,
}

// ── SystemControlEvent ─────────────────────────────────────────────────────

/// A system-level command.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemControlEvent {
    pub command: String, // "START" | "STOP" | "RESTART"
    pub target: Option<String>,
    pub reason: String,
    pub timestamp_micros: i64,
}

// ── Helpers ────────────────────────────────────────────────────────────────

impl RatEvent {
    /// Extract the subject this event should be published under.
    pub fn default_subject(&self) -> String {
        match self {
            RatEvent::Signal(e) => format!("signal.{}", e.symbol),
            RatEvent::MarketPrice(e) => format!("market.price.{}", e.symbol),
            RatEvent::PortfolioSnapshot(_) => "portfolio.snapshot".to_string(),
            RatEvent::Health(e) => format!("health.{}", e.service),
            RatEvent::SystemControl(_) => "system.control".to_string(),
        }
    }

    /// Human-readable summary for logging.
    pub fn summary(&self) -> String {
        match self {
            RatEvent::Signal(e) => {
                format!("Signal {} {} @ {:.2} (conf={:.2})", e.symbol, e.action, e.entry_price, e.confidence)
            }
            RatEvent::MarketPrice(e) => {
                format!("Price {} @ {:.2} [{}]", e.symbol, e.price, e.exchange)
            }
            RatEvent::PortfolioSnapshot(e) => {
                format!("Portfolio equity={:.2} cash={:.2} pnl={:.2}", e.total_equity, e.cash_balance, e.daily_pnl)
            }
            RatEvent::Health(e) => {
                format!("Health {} healthy={}", e.service, e.healthy)
            }
            RatEvent::SystemControl(e) => {
                format!("Control {} reason={}", e.command, e.reason)
            }
        }
    }
}
