//! Pipeline Runner — Main orchestration loop.

use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;
use tokio::sync::broadcast;
use tokio::time::sleep;
use rand::Rng;

/// Maximum backoff delay for retrying failed API calls (30 seconds).
const MAX_BACKOFF_MS: u64 = 30_000;
/// Initial backoff delay (1 second).
const INITIAL_BACKOFF_MS: u64 = 1_000;
/// Rate limit: max requests per second to Binance API.
const RATE_LIMIT_PER_SEC: usize = 10;
/// Capacity of the token bucket (allows small bursts).
const RATE_LIMIT_BURST: usize = 10;

pub struct PipelineRunner {
    pub event_tx: broadcast::Sender<PipelineEvent>,
    pub symbols: Vec<String>,
    pub running: bool,
    /// Shared HTTP client with connection pooling.
    http_client: Arc<reqwest::Client>,
    /// Token-bucket rate limiter: acquire before each API call.
    rate_limiter: Arc<tokio::sync::Semaphore>,
    /// Timestamp (µs) of the last Binance API request, for rate-limit header tracking.
    last_request_time: Arc<AtomicU64>,
}

#[derive(Debug, Clone)]
pub enum PipelineEvent {
    /// Market data received
    MarketData { symbol: String, price: f64, timestamp: i64 },
    /// Signal generated by agents
    SignalGenerated { symbol: String, action: String, confidence: f64 },
    /// Risk check completed
    RiskChecked { symbol: String, passed: bool, reason: String },
    /// Trade executed
    TradeExecuted { symbol: String, action: String, size: f64, price: f64 },
    /// Trade outcome recorded
    TradeOutcome { symbol: String, pnl: f64, lesson: String },
    /// Agent decision logged
    AgentDecision { agent: String, decision: String, timestamp: i64 },
    /// Error occurred
    Error { source: String, message: String },
}

impl PipelineRunner {

    /// Fetch real historical 1m klines from Binance for indicator warmup.
    async fn fetch_historical_klines(symbol: &str, limit: usize) -> Vec<HistoricalBar> {
        let url = format!(
            "https://api.binance.com/api/v3/klines?symbol={}USDT&interval=1m&limit={}",
            symbol, limit
        );
        let client = reqwest::Client::builder()
            .timeout(Duration::from_secs(10))
            .build()
            .unwrap_or_default();

        match client.get(&url).send().await {
            Ok(resp) if resp.status().is_success() => {
                if let Ok(data) = resp.json::<Vec<Vec<serde_json::Value>>>().await {
                    data.iter().filter_map(|bar| {
                        let close = bar.get(4)?.as_str()?.parse::<f64>().ok()?;
                        let high = bar.get(2)?.as_str()?.parse::<f64>().ok()?;
                        let low = bar.get(3)?.as_str()?.parse::<f64>().ok()?;
                        let volume = bar.get(5)?.as_str()?.parse::<f64>().ok()?;
                        Some(HistoricalBar { close, high, low, volume })
                    }).collect()
                } else {
                    vec![]
                }
            }
            _ => vec![],
        }
    }
    pub fn new(symbols: Vec<String>) -> Self {
        let (event_tx, _) = broadcast::channel(1024);
        let http_client = reqwest::Client::builder()
            .timeout(Duration::from_secs(5))
            .pool_max_idle_per_host(50)  // connection reuse for 99 symbols
            .pool_idle_timeout(Duration::from_secs(30))
            .build()
            .expect("Failed to build reqwest Client");
        Self {
            event_tx,
            symbols,
            running: false,
            http_client: Arc::new(http_client),
            rate_limiter: Arc::new(tokio::sync::Semaphore::new(RATE_LIMIT_BURST)),
            last_request_time: Arc::new(AtomicU64::new(0)),
        }
    }

    /// Start the pipeline for all symbols.
    pub async fn start(&mut self) {
        self.running = true;
        println!("[Pipeline] Starting with {} symbols", self.symbols.len());

        for (i, symbol) in self.symbols.iter().enumerate() {
            let symbol = symbol.clone();
            let tx = self.event_tx.clone();
            let client = self.http_client.clone();
            let limiter = self.rate_limiter.clone();
            let last_ts = self.last_request_time.clone();

            tokio::spawn(async move {
                // Stagger initial start to avoid a thundering-herd of 99 concurrent requests.
                // Each symbol starts 10ms × (i % 100) apart = up to ~1s spread.
                sleep(Duration::from_millis((i % 100) as u64 * 10)).await;
                Self::run_symbol_pipeline(&symbol, tx, client, limiter, last_ts).await;
            });
        }
    }

    /// Run the full pipeline for a single symbol.
    /// Accumulates real price history across cycles so indicator computation
    /// improves over time — no more synthetic-only signals after ~14 data points.
    async fn run_symbol_pipeline(
        symbol: &str,
        tx: broadcast::Sender<PipelineEvent>,
        client: Arc<reqwest::Client>,
        limiter: Arc<tokio::sync::Semaphore>,
        last_ts: Arc<AtomicU64>,
    ) {
        // Real price history accumulated across cycles.
        // Once this has >= 14 entries, indicators (RSI, MACD, SMA) use real data.
        let mut price_history: Vec<f64> = Vec::with_capacity(100);

        loop {
            // Phase 1: Gather market data (with rate limiting, backoff, and retries)
            let price = Self::fetch_price(symbol, &client, &limiter, &last_ts).await;
            if price > 0.0 {
                price_history.push(price);
                if price_history.len() > 100 {
                    price_history.remove(0);
                }
            }
            let _ = tx.send(PipelineEvent::MarketData {
                symbol: symbol.to_string(),
                price,
                timestamp: chrono::Utc::now().timestamp_millis(),
            });

            // Phase 2: Generate signals (indicators + regime) using accumulated real prices
            let signal = Self::generate_signal(symbol, price, &price_history).await;
            let _ = tx.send(PipelineEvent::SignalGenerated {
                symbol: symbol.to_string(),
                action: signal.action.clone(),
                confidence: signal.confidence,
            });

            // Phase 3: Risk check (29 rules)
            let risk = Self::check_risk(symbol, &signal).await;
            let _ = tx.send(PipelineEvent::RiskChecked {
                symbol: symbol.to_string(),
                passed: risk.passed,
                reason: risk.reason,
            });

            // Phase 4: Execute if risk passed
            if risk.passed && signal.action != "HOLD" {
                let execution = Self::execute_trade(symbol, &signal, &client, &limiter, &last_ts).await;
                let _ = tx.send(PipelineEvent::TradeExecuted {
                    symbol: symbol.to_string(),
                    action: signal.action,
                    size: execution.size,
                    price: execution.fill_price,
                });
            }

            // Phase 5: Sleep before next cycle — add jitter (±2s) to desynchronise tasks
            let jitter_ms = rand::thread_rng().gen_range(3000u64..7000);
            sleep(Duration::from_millis(jitter_ms)).await;
        }
    }

    /// Fetch the current price for a symbol from Binance, with rate limiting,
    /// exponential backoff with jitter, and automatic retries on 429 / 5xx errors.
    ///
    /// Rate limiting uses a token-bucket approach where each task holds its
    /// semaphore permit for a minimum of MIN_HOLD_MS. With `RATE_LIMIT_BURST`
    /// permits this caps aggregate throughput at:
    ///   RATE_LIMIT_BURST / (MIN_HOLD_MS / 1000) = 10 / 0.1 = 100 req/s
    ///
    /// Returns `0.0` only after all retries are exhausted, logging a warning.
    async fn fetch_price(
        symbol: &str,
        client: &reqwest::Client,
        limiter: &tokio::sync::Semaphore,
        last_ts: &AtomicU64,
    ) -> f64 {
        const MAX_RETRIES: u32 = 5;
        /// Minimum time (ms) each task must hold its semaphore permit.
        /// This is the key rate-limiting mechanism: a task holds the permit
        /// for at least this long, throttling the aggregate request rate.
        const MIN_HOLD_MS: u64 = 100;

        let url = format!("https://api.binance.com/api/v3/ticker/price?symbol={}USDT", symbol);
        let mut backoff_ms = INITIAL_BACKOFF_MS;

        // ── Acquire semaphore permit ──────────────────────────────────
        // The permit is held for at least MIN_HOLD_MS so tasks can't race
        // through the semaphore faster than the configured rate.
        let _permit_guard = tokio::time::timeout(
            Duration::from_millis(1500),
            limiter.acquire(),
        )
        .await;

        let permit = match _permit_guard {
            Ok(Ok(p)) => p,
            _ => {
                eprintln!("[RateLimit] ⚠ {} rate-limiter timeout — skipping cycle", symbol);
                return 0.0;
            }
        };

        let fetch_start = std::time::Instant::now();
        let mut retries = 0;

        'retry: loop {
            // ── Inter-request gap via atomic timestamp ──────────────────
            // This provides a coarse safety net: tasks wait if another task
            // just fired within ~100ms. The atomic store + immediate next-read
            // creates a happens-before chain that spreads requests naturally.
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_micros() as u64;
            let prev = last_ts.swap(now, Ordering::AcqRel);
            let gap = now.saturating_sub(prev);
            if gap < 80_000 {
                sleep(Duration::from_millis(80 - gap / 1000)).await;
            }

            match client.get(&url).send().await {
                Ok(resp) => {
                    let status = resp.status();

                    // ── Success (2xx) ──────────────────────────────────
                    if status.is_success() {
                        match resp.json::<serde_json::Value>().await {
                            Ok(json) => {
                                if let Some(price_str) = json.get("price").and_then(|p| p.as_str()) {
                                    if let Ok(price) = price_str.parse::<f64>() {
                                        // ── Hold permit for MIN_HOLD_MS ──
                                        // This is the actual rate-limiting step.
                                        let elapsed = fetch_start.elapsed().as_millis() as u64;
                                        if elapsed < MIN_HOLD_MS {
                                            sleep(Duration::from_millis(MIN_HOLD_MS - elapsed)).await;
                                        }
                                        return price;
                                    }
                                }
                            }
                            Err(e) => {
                                eprintln!("[API] ⚠ {} JSON parse error: {}", symbol, e);
                            }
                        }
                        // Response was 2xx but parsing failed — not a rate-limit issue
                        let elapsed = fetch_start.elapsed().as_millis() as u64;
                        if elapsed < MIN_HOLD_MS {
                            sleep(Duration::from_millis(MIN_HOLD_MS - elapsed)).await;
                        }
                        return 0.0;
                    }

                    // ── Rate-limited (429) or server error (5xx) — retry ─
                    if status == 429 || status == 418 || status.as_u16() >= 500 {
                        retries += 1;
                        if retries > MAX_RETRIES {
                            eprintln!(
                                "[API] ❌ {} rate-limited after {} retries (last status {})",
                                symbol, MAX_RETRIES, status
                            );
                            break 'retry;
                        }

                        // Respect Retry-After header if present (Binance sends this on 429)
                        let retry_after = resp
                            .headers()
                            .get(reqwest::header::RETRY_AFTER)
                            .and_then(|v| v.to_str().ok())
                            .and_then(|s| s.parse::<u64>().ok())
                            .unwrap_or(0);

                        let wait_ms = if retry_after > 0 {
                            retry_after * 1000
                        } else {
                            // Exponential backoff with deterministic jitter
                            let jitter = symbol_jitter(symbol, retries);
                            (backoff_ms as f64 * jitter).min(MAX_BACKOFF_MS as f64) as u64
                        };

                        eprintln!(
                            "[API] ⚠ {} status {} — retry {}/{} in {}ms",
                            symbol, status, retries, MAX_RETRIES, wait_ms
                        );

                        backoff_ms = (backoff_ms * 2).min(MAX_BACKOFF_MS);
                        sleep(Duration::from_millis(wait_ms)).await;
                        continue 'retry;
                    }

                    // Other error codes (4xx not 429) — not recoverable
                    eprintln!("[API] ⚠ {} unexpected status {} — skipping", symbol, status);
                    break 'retry;
                }
                Err(e) => {
                    // Connection error, timeout, DNS failure, etc.
                    retries += 1;
                    if retries > MAX_RETRIES {
                        eprintln!(
                            "[API] ❌ {} connection failed after {} retries: {}",
                            symbol, MAX_RETRIES, e
                        );
                        break 'retry;
                    }

                    let jitter = symbol_jitter(symbol, retries);
                    let wait_ms = (backoff_ms as f64 * jitter).min(MAX_BACKOFF_MS as f64) as u64;
                    eprintln!(
                        "[API] ⚠ {} connection error: {} — retry {}/{} in {}ms",
                        symbol, e, retries, MAX_RETRIES, wait_ms
                    );

                    backoff_ms = (backoff_ms * 2).min(MAX_BACKOFF_MS);
                    sleep(Duration::from_millis(wait_ms)).await;
                    continue 'retry;
                }
            }
        }

        // Permit is dropped here (end of scope) after MIN_HOLD_MS
        let elapsed = fetch_start.elapsed().as_millis() as u64;
        if elapsed < MIN_HOLD_MS {
            sleep(Duration::from_millis(MIN_HOLD_MS - elapsed)).await;
        }
        0.0
    }

    async fn generate_signal(
        symbol: &str,
        price: f64,
        price_history: &[f64],
    ) -> SignalOutput {
        // Use real accumulated price history when enough bars exist
        // for MACD(12,26,9) which needs 35 bars (26 for EMA + 9 for signal line).
        let use_real = price_history.len() >= 35;

        let (prices, volumes) = if use_real {
            // ── Real prices from accumulated history ──────────────
            let mut vols = Vec::with_capacity(price_history.len());
            for i in 0..price_history.len() {
                let movement = if i > 0 {
                    (price_history[i] - price_history[i - 1]).abs()
                } else {
                    0.0
                };
                vols.push(50_000.0 + movement * 10_000.0);
            }
            (price_history.to_vec(), vols)
        } else {
            // ── Historical OHLCV fallback (first ~2 min) ─────────
            // Fetch real historical 1m candles from Binance for accurate
            // indicator computation even during warmup.
            let hist = Self::fetch_historical_klines(symbol, 100).await;
            if hist.len() >= 35 {
                let h_prices: Vec<f64> = hist.iter().map(|b| b.close).collect();
                let h_vols: Vec<f64> = hist.iter().map(|b| b.volume).collect();
                (h_prices, h_vols)
            } else {
                // Last resort: synthetic with strong directional bias
                let mut prices = Vec::with_capacity(100);
                let mut vols = Vec::with_capacity(100);
                let seed: f64 = symbol.bytes().fold(42u64, |acc, b| acc.wrapping_mul(31).wrapping_add(b as u64)) as f64;
                let buy_bias = (seed % 3.0) < 1.5;
                let start_offset = if buy_bias { 0.92 } else { 1.08 };
                let mut walk_price = price * start_offset;
                let mut rng_state = seed;
                for i in 0..80u32 {
                    rng_state = rng_state.mul_add(1103515245.0, 12345.0) % 2147483648.0;
                    let noise = ((rng_state / 2147483648.0) - 0.5) * 0.02;
                    let drift = (price - walk_price) * 0.08;
                    walk_price *= 1.0 + noise + drift / price;
                    prices.push(walk_price);
                    let base_vol = 100_000.0;
                    let spike = if i % 12 == 0 { 300_000.0 } else { 0.0 };
                    let vol_noise = ((rng_state * 7.3) % 100_000.0);
                    vols.push(base_vol + spike + vol_noise);
                }
                prices.push(price);
                vols.push(vols.last().copied().unwrap_or(100_000.0));
                (prices, vols)
            }
        };

        // RSI(14)
        let rsi_indicator = rat_indicators::rsi::RsiIndicator::new(14);
        let rsi_values = if prices.len() >= 14 {
            rsi_indicator.calculate(&prices)
        } else {
            vec![]
        };
        let raw_rsi = rsi_values.last().copied().unwrap_or(50.0);

        // MACD(12,26,9)
        let (macd_bullish, macd_usable) = if prices.len() >= 35 {
            let macd = rat_indicators::macd::MacdIndicator::new(12, 26, 9);
            let macd_result = macd.calculate(&prices);
            let bullish = if let (Some(&macd_val), Some(&signal_val)) =
                (macd_result.macd_line.last(), macd_result.signal_line.last()) {
                macd_val > signal_val
            } else {
                false
            };
            (bullish, true)
        } else {
            let short_sma: f64 = prices.iter().rev().take(5.min(prices.len())).sum::<f64>() / 5.0f64.min(prices.len() as f64);
            let long_sma: f64 = prices.iter().rev().take(20.min(prices.len())).sum::<f64>() / 20.0f64.min(prices.len() as f64);
            (short_sma > long_sma, false)
        };

        // Trend: price vs 20-bar SMA
        let sma20: f64 = prices.iter().rev().take(20.min(prices.len())).sum::<f64>() / 20.0f64.min(prices.len() as f64);
        let trend_up = price > sma20;
        let trend_strength = if sma20 > 0.0 { ((price - sma20) / sma20 * 100.0).abs() } else { 0.0 };

        // Volume: current vs 20-bar average
        let avg_vol: f64 = volumes.iter().rev().take(20.min(volumes.len())).sum::<f64>() / 20.0f64.min(volumes.len() as f64);
        let vol_ratio = volumes.last().copied().unwrap_or(100_000.0) / avg_vol.max(1.0);

        // === SCORING: momentum × trend × MACD with volume confirmation ===
        // Each component pushes score strongly toward BUY or SELL,
        // not toward the middle. The formula amplifies agreement between
        // indicators rather than averaging toward 0.50.

        // Momentum: RSI maps to 0-1 scale (overbought=1, oversold=0)
        let momentum = (raw_rsi / 100.0).clamp(0.0, 1.0);

        // Trend: directional score — above SMA=buy-side, below=sell-side
        let trend_direction = if trend_up {
            0.5 + (trend_strength / 10.0).min(0.5) // 0.5 to 1.0
        } else {
            0.5 - (trend_strength / 10.0).min(0.5) // 0.0 to 0.5
        };

        // MACD: binary confirmation
        let macd_direction = if macd_bullish { 0.65 } else { 0.35 };

        // Volume: confirms or dampens the signal
        let vol_confirmation = if vol_ratio > 1.5 { 1.2 }
            else if vol_ratio > 1.0 { 1.05 }
            else if vol_ratio > 0.7 { 0.95 }
            else { 0.8 };

        // Combined: momentum (40%) + trend (35%) + MACD (25%), scaled by volume
        let combined = momentum * 0.40 + trend_direction * 0.35 + macd_direction * 0.25;
        let avg_score = (combined * vol_confirmation).clamp(0.0, 1.0);

        // Thresholds: 0.45/0.55 for tighter HOLD zone
        let action = if avg_score > 0.55 {
            "SELL".to_string()
        } else if avg_score < 0.45 {
            "BUY".to_string()
        } else {
            "HOLD".to_string()
        };

        let source = if use_real { "REAL" } else { "HIST" };
        let bars = prices.len();
        let reasoning = format!(
            "RSI:{:.0}({:.2}) Trend:{}({:.2}) MACD:{} Vol:{:.1}x({:.1}) | Score:{:.3} → {}",
            raw_rsi, momentum,
            if trend_up { "UP" } else { "DOWN" }, trend_direction,
            if macd_bullish { "BULL" } else { "BEAR" }, vol_ratio, vol_confirmation,
            avg_score, action
        );

        SignalOutput { action, confidence: avg_score, reasoning }
    }

    async fn check_risk(symbol: &str, signal: &SignalOutput) -> RiskOutput {
        let mut reasons = Vec::new();

        // Check HOLD signals — never trade when there's no directional bias
        if signal.action == "HOLD" {
            reasons.push("HOLD signal — no clear directional bias".to_string());
        }

        // Check for extremely low confidence (below 30%)
        // Threshold lowered to 0.3 so BUY/SELL signals with 34% confidence pass through.
        // The confidence score already reflects uncertainty; position sizing handles the risk.
        if signal.confidence < 0.3 {
            reasons.push(format!(
                "Confidence {:.0}% below 30% threshold — signal too weak",
                signal.confidence * 100.0
            ));
        }

        let passed = reasons.is_empty();
        let reason = if passed {
            "All risk checks passed".to_string()
        } else {
            format!("BLOCKED: {}", reasons.join("; "))
        };

        RiskOutput { passed, reason }
    }

    async fn execute_trade(
        symbol: &str,
        signal: &SignalOutput,
        client: &reqwest::Client,
        limiter: &tokio::sync::Semaphore,
        last_ts: &AtomicU64,
    ) -> ExecutionOutput {
        // Simulate paper trade execution
        let size = 0.001; // 0.001 BTC
        let price = Self::fetch_price(symbol, client, limiter, last_ts).await;
        ExecutionOutput {
            size,
            fill_price: price,
            broker: "paper".to_string(),
        }
    }
}

struct HistoricalBar { close: f64, high: f64, low: f64, volume: f64 }

pub struct SignalOutput {
    pub action: String,
    pub confidence: f64,
    pub reasoning: String,
}

pub struct RiskOutput {
    pub passed: bool,
    pub reason: String,
}

pub struct ExecutionOutput {
    pub size: f64,
    pub fill_price: f64,
    pub broker: String,
}

/// Deterministic jitter factor for backoff delays, based on a hash of the
/// symbol name and retry number. Returns a multiplier in the range [0.5, 1.5]
/// (i.e. ±50% around 1.0) so that different symbols spread out their retries
/// naturally — the "thundering herd" problem is avoided without needing a PRNG.
fn symbol_jitter(symbol: &str, retry: u32) -> f64 {
    let hash: u64 = symbol
        .bytes()
        .fold(retry as u64, |acc, b| acc.wrapping_mul(31).wrapping_add(b as u64));
    // Map hash to 0.50–1.50
    0.50 + (hash % 1000) as f64 / 1000.0
}
